//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.eAccounting.Web.UserControls.DocumentEditor {
    
    
    public partial class FixedAdvanceDocumentEditor {
        
        /// <summary>
        /// ctlInlineScript control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SS.Standard.UI.InlineScript ctlInlineScript;
        
        /// <summary>
        /// ctlUpdatePanelHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelHeader;
        
        /// <summary>
        /// ctlUpdatePanelHeaderProgress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress ctlUpdatePanelHeaderProgress;
        
        /// <summary>
        /// ctlFixedAdvanceFormHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.DocumentEditor.Components.DocumentHeader ctlFixedAdvanceFormHeader;
        
        /// <summary>
        /// ctlFixedAdvanceType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlFixedAdvanceType;
        
        /// <summary>
        /// ctlCompanyText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlCompanyText;
        
        /// <summary>
        /// ctlCompanyReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlCompanyReq;
        
        /// <summary>
        /// ctlCompanyField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.LOV.SCG.DB.CompanyField ctlCompanyField;
        
        /// <summary>
        /// ctlCompanyFieldExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlCompanyFieldExtender;
        
        /// <summary>
        /// ctlSubjectText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlSubjectText;
        
        /// <summary>
        /// ctlSubjectReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlSubjectReq;
        
        /// <summary>
        /// ctlSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlSubject;
        
        /// <summary>
        /// ctlSubjectExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlSubjectExtender;
        
        /// <summary>
        /// ctlCreatorData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.DocumentEditor.Components.ActorData ctlCreatorData;
        
        /// <summary>
        /// ctlRequesterData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.DocumentEditor.Components.ActorData ctlRequesterData;
        
        /// <summary>
        /// ctlReceiverData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.DocumentEditor.Components.ActorData ctlReceiverData;
        
        /// <summary>
        /// UpdatePanelAdvanceTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelAdvanceTab;
        
        /// <summary>
        /// ctlAdvanceTabContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabContainer ctlAdvanceTabContainer;
        
        /// <summary>
        /// ctlTabGeneral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel ctlTabGeneral;
        
        /// <summary>
        /// ctlGeneralLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlGeneralLabel;
        
        /// <summary>
        /// ctlUpdatePanelGeneral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelGeneral;
        
        /// <summary>
        /// ctlUpdateProgressGeneral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress ctlUpdateProgressGeneral;
        
        /// <summary>
        /// ctlFixedAdvanceTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlFixedAdvanceTypeLabel;
        
        /// <summary>
        /// New control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton New;
        
        /// <summary>
        /// LabelExtender1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender1;
        
        /// <summary>
        /// Adjust control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton Adjust;
        
        /// <summary>
        /// LabelExtender2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender2;
        
        /// <summary>
        /// DivRefFixedAdvance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivRefFixedAdvance;
        
        /// <summary>
        /// ctlReferredFixedAdvanceText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlReferredFixedAdvanceText;
        
        /// <summary>
        /// refRequre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label refRequre;
        
        /// <summary>
        /// ctlReferredFixedAdvance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlReferredFixedAdvance;
        
        /// <summary>
        /// LabelExtender4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender4;
        
        /// <summary>
        /// ctlDivDomesticAmount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ctlDivDomesticAmount;
        
        /// <summary>
        /// ctlEffectiveFromText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlEffectiveFromText;
        
        /// <summary>
        /// ctlEffectiveFromReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlEffectiveFromReq;
        
        /// <summary>
        /// ctlEffectiveDateFrom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.CalendarForFixedAdvance ctlEffectiveDateFrom;
        
        /// <summary>
        /// ctlEffectiveDateFromDummy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlEffectiveDateFromDummy;
        
        /// <summary>
        /// LabelExtender5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender5;
        
        /// <summary>
        /// ctlEffectiveToText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlEffectiveToText;
        
        /// <summary>
        /// ctlEffectiveToReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlEffectiveToReq;
        
        /// <summary>
        /// ctlEffectiveDateTo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.Calendar ctlEffectiveDateTo;
        
        /// <summary>
        /// ctlEffectiveDateToDummy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlEffectiveDateToDummy;
        
        /// <summary>
        /// LabelExtender6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender6;
        
        /// <summary>
        /// DivPrevionsAmount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivPrevionsAmount;
        
        /// <summary>
        /// ctlPrevionsAmount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPrevionsAmount;
        
        /// <summary>
        /// ctlPrevionsAmountValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlPrevionsAmountValue;
        
        /// <summary>
        /// LabelExtender10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender10;
        
        /// <summary>
        /// ctlAmount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlAmount;
        
        /// <summary>
        /// ctlAmountValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlAmountValue;
        
        /// <summary>
        /// LabelExtender7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender7;
        
        /// <summary>
        /// ctlAmountGetValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlAmountGetValue;
        
        /// <summary>
        /// DivCtlNetReceive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivCtlNetReceive;
        
        /// <summary>
        /// ctlNetReceive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlNetReceive;
        
        /// <summary>
        /// ctlPayBackCompany control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPayBackCompany;
        
        /// <summary>
        /// ctlReceiveCashFromCompany control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlReceiveCashFromCompany;
        
        /// <summary>
        /// ctlNetReceiveValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlNetReceiveValue;
        
        /// <summary>
        /// LabelExtender11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender11;
        
        /// <summary>
        /// ctrObjective control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctrObjective;
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;
        
        /// <summary>
        /// ctlObjectiveValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlObjectiveValue;
        
        /// <summary>
        /// LabelExtender8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender8;
        
        /// <summary>
        /// ctlRequestDateText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlRequestDateText;
        
        /// <summary>
        /// ctlRequestDateReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlRequestDateReq;
        
        /// <summary>
        /// ctlRequestDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.Calendar ctlRequestDate;
        
        /// <summary>
        /// LabelExtender9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender9;
        
        /// <summary>
        /// ctlDivDomesticPaymentType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ctlDivDomesticPaymentType;
        
        /// <summary>
        /// ctlPaymentTypeText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPaymentTypeText;
        
        /// <summary>
        /// ctlPaymentTypeReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPaymentTypeReq;
        
        /// <summary>
        /// ctlPaymentType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlPaymentType;
        
        /// <summary>
        /// ctlPaymentTypeExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlPaymentTypeExtender;
        
        /// <summary>
        /// ctlDivCounterCashierDomesticText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ctlDivCounterCashierDomesticText;
        
        /// <summary>
        /// ctlCounterCashierInterText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlCounterCashierInterText;
        
        /// <summary>
        /// ctlCounterCashier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlCounterCashier;
        
        /// <summary>
        /// ctlCounterCashierExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlCounterCashierExtender;
        
        /// <summary>
        /// ctlDivServiceTeam control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ctlDivServiceTeam;
        
        /// <summary>
        /// ctlServiceText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlServiceText;
        
        /// <summary>
        /// ctlServiceReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlServiceReq;
        
        /// <summary>
        /// ctlServiceTeam control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlServiceTeam;
        
        /// <summary>
        /// ctlServiceTeamExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlServiceTeamExtender;
        
        /// <summary>
        /// divreturnMedthod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divreturnMedthod;
        
        /// <summary>
        /// ReturnMethodLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnMethodLabel;
        
        /// <summary>
        /// ReturnRequestDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnRequestDate;
        
        /// <summary>
        /// ReturnRequestDateReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnRequestDateReq;
        
        /// <summary>
        /// LabelExtender12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender12;
        
        /// <summary>
        /// ctlReturnRequestDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.Calendar ctlReturnRequestDate;
        
        /// <summary>
        /// LabelExtender3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender3;
        
        /// <summary>
        /// ReturnPaymentDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ReturnPaymentDiv;
        
        /// <summary>
        /// ReturnPaymentText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnPaymentText;
        
        /// <summary>
        /// ReturnPaymentReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnPaymentReq;
        
        /// <summary>
        /// LabelExtender13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender13;
        
        /// <summary>
        /// ctlReturnPaymentType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlReturnPaymentType;
        
        /// <summary>
        /// ReturnPaymentLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ReturnPaymentLabel;
        
        /// <summary>
        /// ReturnCounterCashierDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ReturnCounterCashierDiv;
        
        /// <summary>
        /// ReturnCounterCashierLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnCounterCashierLabel;
        
        /// <summary>
        /// ctlReturnCounterCashier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlReturnCounterCashier;
        
        /// <summary>
        /// ctlReturnCounterCashierExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlReturnCounterCashierExtender;
        
        /// <summary>
        /// ReturnServiceTeamDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ReturnServiceTeamDiv;
        
        /// <summary>
        /// ReturnServiceTeamLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnServiceTeamLabel;
        
        /// <summary>
        /// ReturnServiceTeamReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnServiceTeamReq;
        
        /// <summary>
        /// LabelExtender14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender14;
        
        /// <summary>
        /// ctlReturnServiceTeam control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlReturnServiceTeam;
        
        /// <summary>
        /// LabelExtender33 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender33;
        
        /// <summary>
        /// ctlTabOutstanding control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel ctlTabOutstanding;
        
        /// <summary>
        /// ctlOutstandingText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlOutstandingText;
        
        /// <summary>
        /// ctlUpdatePanelOutstanding control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelOutstanding;
        
        /// <summary>
        /// ctlOutstandingGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SS.Standard.UI.BaseGridView ctlOutstandingGrid;
        
        /// <summary>
        /// FixedAdvanceOutstandingGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SS.Standard.UI.BaseGridView FixedAdvanceOutstandingGrid;
        
        /// <summary>
        /// ctlTabInitial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel ctlTabInitial;
        
        /// <summary>
        /// ctlTabInitialText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlTabInitialText;
        
        /// <summary>
        /// ctlUpdatePanelInitial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelInitial;
        
        /// <summary>
        /// ctlUpdateProgressInitial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress ctlUpdateProgressInitial;
        
        /// <summary>
        /// ctlInitiator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.DocumentEditor.Components.Initiator ctlInitiator;
        
        /// <summary>
        /// ctlTabAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel ctlTabAttachment;
        
        /// <summary>
        /// ctlTabAttachmentText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlTabAttachmentText;
        
        /// <summary>
        /// ctlUpdatePanelAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelAttachment;
        
        /// <summary>
        /// ctlUpdateProgressAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress ctlUpdateProgressAttachment;
        
        /// <summary>
        /// ctlAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.DocumentEditor.Components.Attachment ctlAttachment;
        
        /// <summary>
        /// ctlTabMemo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel ctlTabMemo;
        
        /// <summary>
        /// ctlTabMemoText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlTabMemoText;
        
        /// <summary>
        /// ctlUpdatePanelMemo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelMemo;
        
        /// <summary>
        /// ctlUpdateProgressMemo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress ctlUpdateProgressMemo;
        
        /// <summary>
        /// ctlMemo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlMemo;
        
        /// <summary>
        /// ctlMemoExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlMemoExtender;
        
        /// <summary>
        /// ctlTabHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel ctlTabHistory;
        
        /// <summary>
        /// ctlTabHistoryText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlTabHistoryText;
        
        /// <summary>
        /// ctlUpdatePanelHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelHistory;
        
        /// <summary>
        /// ctlUpdateProgressHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress ctlUpdateProgressHistory;
        
        /// <summary>
        /// ctlHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.DocumentEditor.Components.History ctlHistory;
        
        /// <summary>
        /// ctlUpdatePanelApprover control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelApprover;
        
        /// <summary>
        /// ctlApproverData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.DocumentEditor.Components.ActorData ctlApproverData;
        
        /// <summary>
        /// AleartMessageFixedAdvance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label AleartMessageFixedAdvance;
        
        /// <summary>
        /// ctlUpdatePanelViewPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelViewPost;
        
        /// <summary>
        /// ctlUpdatePanelViewPostProgress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress ctlUpdatePanelViewPostProgress;
        
        /// <summary>
        /// ctlDivViewDetailDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ctlDivViewDetailDomestic;
        
        /// <summary>
        /// ctlFieldSetVerifyDetailDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ctlFieldSetVerifyDetailDomestic;
        
        /// <summary>
        /// ctlVerifyDetailDomesticHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlVerifyDetailDomesticHeader;
        
        /// <summary>
        /// ctlBranchTextDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlBranchTextDomestic;
        
        /// <summary>
        /// ctlBranchDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlBranchDomestic;
        
        /// <summary>
        /// ctlBranchDomesticExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlBranchDomesticExtender;
        
        /// <summary>
        /// ctlPaymentMethodDomesticText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPaymentMethodDomesticText;
        
        /// <summary>
        /// ctlPaymentMethodDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlPaymentMethodDomestic;
        
        /// <summary>
        /// ctlPaymentMethodDomesticExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlPaymentMethodDomesticExtender;
        
        /// <summary>
        /// ctlDivSupplementFixedAdvance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ctlDivSupplementFixedAdvance;
        
        /// <summary>
        /// ctlSupplementaryDomesticText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlSupplementaryDomesticText;
        
        /// <summary>
        /// ctlSupplementary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlSupplementary;
        
        /// <summary>
        /// ctlSupplementaryLabelExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlSupplementaryLabelExtender;
        
        /// <summary>
        /// ctlViewPostButtonDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ctlViewPostButtonDomestic;
        
        /// <summary>
        /// ctlPostingDateDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPostingDateDomestic;
        
        /// <summary>
        /// ctlPostingDateCalendarDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.Calendar ctlPostingDateCalendarDomestic;
        
        /// <summary>
        /// ctlPostingDateCalendarDomesticExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender ctlPostingDateCalendarDomesticExtender;
        
        /// <summary>
        /// ctlBaselineDateDomesticText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlBaselineDateDomesticText;
        
        /// <summary>
        /// ctlBaselineDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlBaselineDate;
        
        /// <summary>
        /// ctlPostingStatusDomesticText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPostingStatusDomesticText;
        
        /// <summary>
        /// ctlPostingStatusDomestic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPostingStatusDomestic;
        
        /// <summary>
        /// DivBankAccountGL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivBankAccountGL;
        
        /// <summary>
        /// BankAccountGLText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BankAccountGLText;
        
        /// <summary>
        /// BankAccountGL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox BankAccountGL;
        
        /// <summary>
        /// LabelExtender18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender18;
        
        /// <summary>
        /// ctlViewPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.ViewPost.ViewPost ctlViewPost;
        
        /// <summary>
        /// ctlUpdatePanelViewPostReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelViewPostReturn;
        
        /// <summary>
        /// UpdateProgress1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
        
        /// <summary>
        /// ctlDivViewDetailDomesticReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ctlDivViewDetailDomesticReturn;
        
        /// <summary>
        /// Fieldset1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Fieldset1;
        
        /// <summary>
        /// VerifyReturnDetailReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label VerifyReturnDetailReturn;
        
        /// <summary>
        /// BranchReturnText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BranchReturnText;
        
        /// <summary>
        /// ctlBranchRetunr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlBranchRetunr;
        
        /// <summary>
        /// LabelExtender15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender15;
        
        /// <summary>
        /// PaymentMethodReturnText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PaymentMethodReturnText;
        
        /// <summary>
        /// ctlPaymentMethodReturnPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlPaymentMethodReturnPost;
        
        /// <summary>
        /// LabelExtender16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender16;
        
        /// <summary>
        /// PostReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button PostReturn;
        
        /// <summary>
        /// PostingDateReturnText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PostingDateReturnText;
        
        /// <summary>
        /// ctlPostingDateReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.Calendar ctlPostingDateReturn;
        
        /// <summary>
        /// LabelExtender17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender17;
        
        /// <summary>
        /// BaselineDateReturnText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BaselineDateReturnText;
        
        /// <summary>
        /// ctlBaselineDateReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlBaselineDateReturn;
        
        /// <summary>
        /// PostingStatusReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PostingStatusReturn;
        
        /// <summary>
        /// ctlPostingStatusReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ctlPostingStatusReturn;
        
        /// <summary>
        /// DivBankAccountText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivBankAccountText;
        
        /// <summary>
        /// BankAccountText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BankAccountText;
        
        /// <summary>
        /// ctlBankAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ctlBankAccount;
        
        /// <summary>
        /// LabelExtender55 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.CustomControls.LabelExtender LabelExtender55;
        
        /// <summary>
        /// ctlViewPostReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCG.eAccounting.Web.UserControls.ViewPost.ViewPost ctlViewPostReturn;
        
        /// <summary>
        /// ctlUpdatePanelValidation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ctlUpdatePanelValidation;
        
        /// <summary>
        /// ctlValidationSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spring.Web.UI.Controls.ValidationSummary ctlValidationSummary;
        
        /// <summary>
        /// ctlValidationSummary1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spring.Web.UI.Controls.ValidationSummary ctlValidationSummary1;
    }
}
