//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SS.DB.DTO
{
	/// <summary>
	/// POJO for DbRegionLang. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class DbRegionLang
	{
		#region Fields
		
		private long id;
		private string regionName;
		private string comment;
		private long updBy;
		private DateTime updDate;
		private long creBy;
		private DateTime creDate;
		private string updPgm;
		private Byte[] rowVersion;
		private bool active;
		private SS.DB.DTO.DbLanguage language;
		private SS.DB.DTO.DbRegion region;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DbRegionLang class
		/// </summary>
		public DbRegionLang()
		{
		}

		public DbRegionLang(long id)
		{
			this.id = id;
		}
	
		/// <summary>
		/// Initializes a new instance of the DbRegionLang class
		/// </summary>
		/// <param name="regionName">Initial <see cref="DbRegionLang.RegionName" /> value</param>
		/// <param name="comment">Initial <see cref="DbRegionLang.Comment" /> value</param>
		/// <param name="updBy">Initial <see cref="DbRegionLang.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="DbRegionLang.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="DbRegionLang.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="DbRegionLang.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="DbRegionLang.UpdPgm" /> value</param>
		/// <param name="rowVersion">Initial <see cref="DbRegionLang.RowVersion" /> value</param>
		/// <param name="active">Initial <see cref="DbRegionLang.Active" /> value</param>
		/// <param name="language">Initial <see cref="DbRegionLang.Language" /> value</param>
		/// <param name="region">Initial <see cref="DbRegionLang.Region" /> value</param>
		public DbRegionLang(string regionName, string comment, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, Byte[] rowVersion, bool active, SS.DB.DTO.DbLanguage language, SS.DB.DTO.DbRegion region)
		{
			this.regionName = regionName;
			this.comment = comment;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.rowVersion = rowVersion;
			this.active = active;
			this.language = language;
			this.region = region;
		}
	
		/// <summary>
		/// Minimal constructor for class DbRegionLang
		/// </summary>
		/// <param name="regionName">Initial <see cref="DbRegionLang.RegionName" /> value</param>
		/// <param name="updBy">Initial <see cref="DbRegionLang.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="DbRegionLang.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="DbRegionLang.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="DbRegionLang.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="DbRegionLang.UpdPgm" /> value</param>
		/// <param name="active">Initial <see cref="DbRegionLang.Active" /> value</param>
		public DbRegionLang(string regionName, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, bool active)
		{
			this.regionName = regionName;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.active = active;
		}
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the Id for the current DbRegionLang
		/// </summary>
		public virtual long Id
		{
			get { return this.id; }
			set { this.id = value; }
		}
		
		/// <summary>
		/// Gets or sets the RegionName for the current DbRegionLang
		/// </summary>
		public virtual string RegionName
		{
			get { return this.regionName; }
			set { this.regionName = value; }
		}
		
		/// <summary>
		/// Gets or sets the Comment for the current DbRegionLang
		/// </summary>
		public virtual string Comment
		{
			get { return this.comment; }
			set { this.comment = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdBy for the current DbRegionLang
		/// </summary>
		public virtual long UpdBy
		{
			get { return this.updBy; }
			set { this.updBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdDate for the current DbRegionLang
		/// </summary>
		public virtual DateTime UpdDate
		{
			get { return this.updDate; }
			set { this.updDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreBy for the current DbRegionLang
		/// </summary>
		public virtual long CreBy
		{
			get { return this.creBy; }
			set { this.creBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current DbRegionLang
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdPgm for the current DbRegionLang
		/// </summary>
		public virtual string UpdPgm
		{
			get { return this.updPgm; }
			set { this.updPgm = value; }
		}
		
		/// <summary>
		/// Gets or sets the RowVersion for the current DbRegionLang
		/// </summary>
		public virtual Byte[] RowVersion
		{
			get { return this.rowVersion; }
			set { this.rowVersion = value; }
		}
		
		/// <summary>
		/// Gets or sets the Active for the current DbRegionLang
		/// </summary>
		public virtual bool Active
		{
			get { return this.active; }
			set { this.active = value; }
		}
		
		/// <summary>
		/// Gets or sets the Language for the current DbRegionLang
		/// </summary>
		public virtual SS.DB.DTO.DbLanguage Language
		{
			get { return this.language; }
			set { this.language = value; }
		}
		
		/// <summary>
		/// Gets or sets the Region for the current DbRegionLang
		/// </summary>
		public virtual SS.DB.DTO.DbRegion Region
		{
			get { return this.region; }
			set { this.region = value; }
		}
		
		#endregion
	}
}
