//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SS.DB.DTO
{
	/// <summary>
	/// POJO for DbRegion. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class DbRegion
	{
		#region Fields
		
		private short regionid;
		private string comment;
		private long updBy;
		private DateTime updDate;
		private long creBy;
		private DateTime creDate;
		private string updPgm;
		private Byte[] rowVersion;
		private bool active;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DbRegion class
		/// </summary>
		public DbRegion()
		{
		}

		public DbRegion(short regionid)
		{
			this.regionid = regionid;
		}
	
		/// <summary>
		/// Initializes a new instance of the DbRegion class
		/// </summary>
		/// <param name="comment">Initial <see cref="DbRegion.Comment" /> value</param>
		/// <param name="updBy">Initial <see cref="DbRegion.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="DbRegion.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="DbRegion.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="DbRegion.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="DbRegion.UpdPgm" /> value</param>
		/// <param name="rowVersion">Initial <see cref="DbRegion.RowVersion" /> value</param>
		/// <param name="active">Initial <see cref="DbRegion.Active" /> value</param>
		public DbRegion(string comment, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, Byte[] rowVersion, bool active)
		{
			this.comment = comment;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.rowVersion = rowVersion;
			this.active = active;
		}
	
		/// <summary>
		/// Minimal constructor for class DbRegion
		/// </summary>
		/// <param name="updBy">Initial <see cref="DbRegion.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="DbRegion.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="DbRegion.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="DbRegion.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="DbRegion.UpdPgm" /> value</param>
		/// <param name="active">Initial <see cref="DbRegion.Active" /> value</param>
		public DbRegion(long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, bool active)
		{
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.active = active;
		}
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the Regionid for the current DbRegion
		/// </summary>
		public virtual short Regionid
		{
			get { return this.regionid; }
			set { this.regionid = value; }
		}
		
		/// <summary>
		/// Gets or sets the Comment for the current DbRegion
		/// </summary>
		public virtual string Comment
		{
			get { return this.comment; }
			set { this.comment = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdBy for the current DbRegion
		/// </summary>
		public virtual long UpdBy
		{
			get { return this.updBy; }
			set { this.updBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdDate for the current DbRegion
		/// </summary>
		public virtual DateTime UpdDate
		{
			get { return this.updDate; }
			set { this.updDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreBy for the current DbRegion
		/// </summary>
		public virtual long CreBy
		{
			get { return this.creBy; }
			set { this.creBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current DbRegion
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdPgm for the current DbRegion
		/// </summary>
		public virtual string UpdPgm
		{
			get { return this.updPgm; }
			set { this.updPgm = value; }
		}
		
		/// <summary>
		/// Gets or sets the RowVersion for the current DbRegion
		/// </summary>
		public virtual Byte[] RowVersion
		{
			get { return this.rowVersion; }
			set { this.rowVersion = value; }
		}
		
		/// <summary>
		/// Gets or sets the Active for the current DbRegion
		/// </summary>
		public virtual bool Active
		{
			get { return this.active; }
			set { this.active = value; }
		}
		
		#endregion
	}
}
