//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SCG.DB.DTO
{
    /// <summary>
    /// POJO for DbExpenseGroup. This class is autogenerated
    /// </summary>
    [Serializable]
    public partial class DbExpenseGroup
    {
        #region Fields
        private long expenseGroupID;
        private string expenseGroupCode;
        private bool active;
        private long updBy;
        private DateTime updDate;
        private long creBy;
        private DateTime creDate;
        private string updPgm;
        private byte[] rowVersion;
        private string description;
        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the DbExpenseGroup class
        /// </summary>
        public DbExpenseGroup()
        {
        }

        public DbExpenseGroup(long expenseGroupID)
        {
            this.expenseGroupID = expenseGroupID;
        }

        /// <summary>
        /// Initializes a new instance of the DbExpenseGroup class
        /// </summary>
        /// <param name="expenseGroupCode">Initial <see cref="DbExpenseGroup.ExpenseGroupCode" /> value</param>
        /// <param name="updBy">Initial <see cref="DbExpenseGroup.UpdBy" /> value</param>
        /// <param name="updDate">Initial <see cref="DbExpenseGroup.UpdDate" /> value</param>
        /// <param name="creBy">Initial <see cref="DbExpenseGroup.CreBy" /> value</param>
        /// <param name="creDate">Initial <see cref="DbExpenseGroup.CreDate" /> value</param>
        /// <param name="updPgm">Initial <see cref="DbExpenseGroup.UpdPgm" /> value</param>
        /// <param name="rowVersion">Initial <see cref="DbExpenseGroup.RowVersion" /> value</param>
        /// <param name="active">Initial <see cref="DbExpenseGroup.Active" /> value</param>
        /// <param name="expenseGroup">Initial <see cref="DbExpenseGroup.ExpenseGroup" /> value</param>
        /// <param name="language">Initial <see cref="DbCountryLang.Language" /> value</param>
        public DbExpenseGroup(string expenseGroupCode, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, byte[] rowVersion, bool active, string description)
        {
            this.expenseGroupCode = expenseGroupCode;
            this.updBy = updBy;
            this.updDate = updDate;
            this.creBy = creBy;
            this.creDate = creDate;
            this.updPgm = updPgm;
            this.rowVersion = rowVersion;
            this.active = active;
            this.description = description;
        }

        /// <summary>
        /// Minimal constructor for class DbExpenseGroup
        /// </summary>
        /// <param name="updBy">Initial <see cref="DbExpenseGroup.UpdBy" /> value</param>
        /// <param name="updDate">Initial <see cref="DbExpenseGroup.UpdDate" /> value</param>
        /// <param name="creBy">Initial <see cref="DbExpenseGroup.CreBy" /> value</param>
        /// <param name="creDate">Initial <see cref="DbExpenseGroup.CreDate" /> value</param>
        /// <param name="updPgm">Initial <see cref="DbExpenseGroup.UpdPgm" /> value</param>
        /// <param name="active">Initial <see cref="DbExpenseGroup.Active" /> value</param>
        public DbExpenseGroup(long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, bool active)
        {
            this.updBy = updBy;
            this.updDate = updDate;
            this.creBy = creBy;
            this.creDate = creDate;
            this.updPgm = updPgm;
            this.active = active;
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets the expenseGroupID for the current DbExpenseGroup
        /// </summary>
        public virtual long ExpenseGroupID
        {
            get { return this.expenseGroupID; }
            set { this.expenseGroupID = value; }
        }

        /// <summary>
        /// Gets or sets the ExpenseGroupCode for the current DbExpenseGroup
        /// </summary>
        public virtual string ExpenseGroupCode
        {
            get { return this.expenseGroupCode; }
            set { this.expenseGroupCode = value; }
        }

        public virtual string Description
        {
            get { return this.description; }
            set { this.description = value; }
        }

        /// <summary>
        /// Gets or sets the UpdBy for the current DbExpenseGroup
        /// </summary>
        public virtual long UpdBy
        {
            get { return this.updBy; }
            set { this.updBy = value; }
        }

        /// <summary>
        /// Gets or sets the UpdDate for the current DbExpenseGroup
        /// </summary>
        public virtual DateTime UpdDate
        {
            get { return this.updDate; }
            set { this.updDate = value; }
        }

        /// <summary>
        /// Gets or sets the CreBy for the current DbExpenseGroup
        /// </summary>
        public virtual long CreBy
        {
            get { return this.creBy; }
            set { this.creBy = value; }
        }

        /// <summary>
        /// Gets or sets the CreDate for the current DbExpenseGroup
        /// </summary>
        public virtual DateTime CreDate
        {
            get { return this.creDate; }
            set { this.creDate = value; }
        }

        /// <summary>
        /// Gets or sets the UpdPgm for the current DbExpenseGroup
        /// </summary>
        public virtual string UpdPgm
        {
            get { return this.updPgm; }
            set { this.updPgm = value; }
        }

        /// <summary>
        /// Gets or sets the RowVersion for the current DbExpenseGroup
        /// </summary>
        public virtual byte[] RowVersion
        {
            get { return this.rowVersion; }
            set { this.rowVersion = value; }
        }

        /// <summary>
        /// Gets or sets the Active for the current DbExpenseGroup
        /// </summary>
        public virtual bool Active
        {
            get { return this.active; }
            set { this.active = value; }
        }

        #endregion
    }
}
