//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SCG.DB.DTO
{
	/// <summary>
	/// POJO for RejectReasonLang. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class RejectReasonLang
	{
		#region Fields
        private long id;
        private string reasonDetail;
		private string comment;
		private long updBy;
		private DateTime updDate;
		private long creBy;
		private DateTime creDate;
		private string updPgm;
		private byte[] rowVersion;
		private bool active;
        private SCG.DB.DTO.RejectReason rejectReason;
        private SS.DB.DTO.DbLanguage language;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the RejectReasonLang class
		/// </summary>
		public RejectReasonLang()
		{
		}

        public RejectReasonLang(short id)
		{
            this.id = id;
		}
	
		/// <summary>
		/// Initializes a new instance of the RejectReasonLang class
		/// </summary>
        /// <param name="reasonDetail">Initial <see cref="RejectReasonLang.reasonDetail" /> value</param>
		/// <param name="comment">Initial <see cref="RejectReasonLang.Comment" /> value</param>
		/// <param name="updBy">Initial <see cref="RejectReasonLang.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="RejectReasonLang.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="RejectReasonLang.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="RejectReasonLang.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="RejectReasonLang.UpdPgm" /> value</param>
		/// <param name="rowVersion">Initial <see cref="RejectReasonLang.RowVersion" /> value</param>
		/// <param name="active">Initial <see cref="RejectReasonLang.Active" /> value</param>
        public RejectReasonLang(string reasonDetail, string comment, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, byte[] rowVersion, bool active)
		{
            this.reasonDetail = reasonDetail;
            this.comment = comment;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.rowVersion = rowVersion;
			this.active = active;
		}
	
		/// <summary>
		/// Minimal constructor for class RejectReasonLang
		/// </summary>
		/// <param name="updBy">Initial <see cref="RejectReasonLang.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="RejectReasonLang.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="RejectReasonLang.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="RejectReasonLang.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="RejectReasonLang.UpdPgm" /> value</param>
		/// <param name="active">Initial <see cref="RejectReasonLang.Active" /> value</param>
        public RejectReasonLang(long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, bool active)
		{
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.active = active;
		}
		#endregion
	
		#region Properties

        /// <summary>
        /// Gets or sets the ID for the current RejectReasonLang
        /// </summary>
        public virtual long ID
        {
            get { return this.id; }
            set { this.id = value; }
        }

		
        /// <summary>
        /// Gets or sets the reasonDetail for the current RejectReasonLang
        /// </summary>
        public virtual string ReasonDetail
        {
            get { return this.reasonDetail; }
            set { this.reasonDetail = value; }
        }
		
		/// <summary>
		/// Gets or sets the Comment for the current RejectReasonLang
		/// </summary>
		public virtual string Comment
		{
			get { return this.comment; }
			set { this.comment = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdBy for the current RejectReasonLang
		/// </summary>
		public virtual long UpdBy
		{
			get { return this.updBy; }
			set { this.updBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdDate for the current RejectReasonLang
		/// </summary>
		public virtual DateTime UpdDate
		{
			get { return this.updDate; }
			set { this.updDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreBy for the current RejectReasonLang
		/// </summary>
		public virtual long CreBy
		{
			get { return this.creBy; }
			set { this.creBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current RejectReasonLang
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdPgm for the current RejectReasonLang
		/// </summary>
		public virtual string UpdPgm
		{
			get { return this.updPgm; }
			set { this.updPgm = value; }
		}
		
		/// <summary>
		/// Gets or sets the RowVersion for the current RejectReasonLang
		/// </summary>
		public virtual byte[] RowVersion
		{
			get { return this.rowVersion; }
			set { this.rowVersion = value; }
		}
		
		/// <summary>
		/// Gets or sets the Active for the current RejectReasonLang
		/// </summary>
		public virtual bool Active
		{
			get { return this.active; }
			set { this.active = value; }
		}

		/// <summary>
		/// Gets or sets the Bank for the current DbBankLang
		/// </summary>
		public virtual SCG.DB.DTO.RejectReason RejectReason
		{
			get { return this.rejectReason; }
            set { this.rejectReason = value; }
		}
		
		/// <summary>
		/// Gets or sets the Language for the current DbBankLang
		/// </summary>
        public virtual SS.DB.DTO.DbLanguage Language
		{
			get { return this.language; }
			set { this.language = value; }
		}
		
		#endregion
	}
}
