//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SCG.DB.DTO
{
	/// <summary>
	/// POJO for RejectReason. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class RejectReason
	{
		#region Fields
        private short reasonID;
        private string reasonCode;
        private string documentTypeCode;
		private string comment;
		private long updBy;
		private DateTime updDate;
		private long creBy;
		private DateTime creDate;
		private string updPgm;
		private byte[] rowVersion;
		private bool active;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the RejectReason class
		/// </summary>
		public RejectReason()
		{
		}

        public RejectReason(short reasonID)
		{
            this.reasonID = reasonID;
		}
	
		/// <summary>
		/// Initializes a new instance of the RejectReason class
		/// </summary>
        /// <param name="reasonCode">Initial <see cref="RejectReason.reasonCode" /> value</param>
        /// <param name="documentTypeCode">Initial <see cref="RejectReason.documentTypeCode" /> value</param>
		/// <param name="comment">Initial <see cref="RejectReason.Comment" /> value</param>
		/// <param name="updBy">Initial <see cref="RejectReason.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="RejectReason.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="RejectReason.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="RejectReason.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="RejectReason.UpdPgm" /> value</param>
		/// <param name="rowVersion">Initial <see cref="RejectReason.RowVersion" /> value</param>
		/// <param name="active">Initial <see cref="RejectReason.Active" /> value</param>
        public RejectReason(string reasonCode,string documentTypeCode, string comment, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, byte[] rowVersion, bool active)
		{
            this.reasonCode = reasonCode;
            this.documentTypeCode = documentTypeCode;
            this.comment = comment;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.rowVersion = rowVersion;
			this.active = active;
		}
	
		/// <summary>
		/// Minimal constructor for class RejectReason
		/// </summary>
        /// <param name="reasonCode">Initial <see cref="RejectReason.reasonCode" /> value</param>
        /// <param name="documentTypeCode">Initial <see cref="RejectReason.documentTypeCode" /> value</param>
		/// <param name="updBy">Initial <see cref="RejectReason.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="RejectReason.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="RejectReason.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="RejectReason.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="RejectReason.UpdPgm" /> value</param>
		/// <param name="active">Initial <see cref="RejectReason.Active" /> value</param>
        public RejectReason(string reasonCode,string documentTypeCode, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, bool active)
		{
            this.reasonCode = reasonCode;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.active = active;
		}
		#endregion
	
		#region Properties
		
		/// <summary>
        /// Gets or sets the ReasonID for the current RejectReason
		/// </summary>
        public virtual short ReasonID
		{
			get { return this.reasonID; }
            set { this.reasonID = value; }
		}
		
		/// <summary>
        /// Gets or sets the reasonCode for the current RejectReason
		/// </summary>
        public virtual string ReasonCode
		{
            get { return this.reasonCode; }
            set { this.reasonCode = value; }
		}

        /// <summary>
        /// Gets or sets the reasonCode for the current RejectReason
        /// </summary>
        public virtual string DocumentTypeCode
        {
            get { return this.documentTypeCode; }
            set { this.documentTypeCode = value; }
        }
		
		/// <summary>
		/// Gets or sets the Comment for the current RejectReason
		/// </summary>
		public virtual string Comment
		{
			get { return this.comment; }
			set { this.comment = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdBy for the current RejectReason
		/// </summary>
		public virtual long UpdBy
		{
			get { return this.updBy; }
			set { this.updBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdDate for the current RejectReason
		/// </summary>
		public virtual DateTime UpdDate
		{
			get { return this.updDate; }
			set { this.updDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreBy for the current RejectReason
		/// </summary>
		public virtual long CreBy
		{
			get { return this.creBy; }
			set { this.creBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current RejectReason
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdPgm for the current RejectReason
		/// </summary>
		public virtual string UpdPgm
		{
			get { return this.updPgm; }
			set { this.updPgm = value; }
		}
		
		/// <summary>
		/// Gets or sets the RowVersion for the current RejectReason
		/// </summary>
		public virtual byte[] RowVersion
		{
			get { return this.rowVersion; }
			set { this.rowVersion = value; }
		}
		
		/// <summary>
		/// Gets or sets the Active for the current RejectReason
		/// </summary>
		public virtual bool Active
		{
			get { return this.active; }
			set { this.active = value; }
		}
		
		#endregion
	}
}
