
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2/4/2552
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Middleware.Connector;
//using SAP.Connector;

namespace SCG.eAccounting.SAP.BAPI
{

    /// <summary>
    /// Posting in accounting: CO-PA acct assignment value fields
    /// </summary>
    //[RfcStructure(AbapName ="BAPIACKEV9" , Length = 76, Length2 = 132)]
    [Serializable]
    public class BAPIACKEV9 //: SAPStructure
    {


        /// <summary>
        /// Accounting Document Line Item Number
        /// </summary>

        //[RfcField(AbapName = "ITEMNO_ACC", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
        //[XmlElement("ITEMNO_ACC", Form=XmlSchemaForm.Unqualified)]
        public string Itemno_Acc
        {
            get
            {
                return _Itemno_Acc;
            }
            set
            {
                _Itemno_Acc = value;
            }
        }
        private string _Itemno_Acc;


        /// <summary>
        /// Field Name
        /// </summary>

        //[RfcField(AbapName = "FIELDNAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 10, Offset2 = 20)]
        //[XmlElement("FIELDNAME", Form=XmlSchemaForm.Unqualified)]
        public string Fieldname
        {
            get
            {
                return _Fieldname;
            }
            set
            {
                _Fieldname = value;
            }
        }
        private string _Fieldname;


        /// <summary>
        /// Currency Type And Valuation View
        /// </summary>

        //[RfcField(AbapName = "CURR_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 40, Offset2 = 80)]
        //[XmlElement("CURR_TYPE", Form=XmlSchemaForm.Unqualified)]
        public string Curr_Type
        {
            get
            {
                return _Curr_Type;
            }
            set
            {
                _Curr_Type = value;
            }
        }
        private string _Curr_Type;


        /// <summary>
        /// Currency Key
        /// </summary>

        //[RfcField(AbapName = "CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 42, Offset2 = 84)]
        //[XmlElement("CURRENCY", Form=XmlSchemaForm.Unqualified)]
        public string Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                _Currency = value;
            }
        }
        private string _Currency;


        /// <summary>
        /// ISO code currency
        /// </summary>

        //[RfcField(AbapName = "CURRENCY_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 47, Offset2 = 94)]
        //[XmlElement("CURRENCY_ISO", Form=XmlSchemaForm.Unqualified)]
        public string Currency_Iso
        {
            get
            {
                return _Currency_Iso;
            }
            set
            {
                _Currency_Iso = value;
            }
        }
        private string _Currency_Iso;


        /// <summary>
        /// Value components: Currency field
        /// </summary>

        //[RfcField(AbapName = "AMT_VALCOM", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 12, Length2 = 12, Decimals = 4, Offset = 50, Offset2 = 100)]
        //[XmlElement("AMT_VALCOM", Form=XmlSchemaForm.Unqualified)]
        public Decimal Amt_Valcom
        {
            get
            {
                return _Amt_Valcom;
            }
            set
            {
                _Amt_Valcom = value;
            }
        }
        private Decimal _Amt_Valcom;


        /// <summary>
        /// Base Unit of Measure
        /// </summary>

        //[RfcField(AbapName = "BASE_UOM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 62, Offset2 = 112)]
        //[XmlElement("BASE_UOM", Form=XmlSchemaForm.Unqualified)]
        public string Base_Uom
        {
            get
            {
                return _Base_Uom;
            }
            set
            {
                _Base_Uom = value;
            }
        }
        private string _Base_Uom;


        /// <summary>
        /// Base unit of measure in ISO code
        /// </summary>

        //[RfcField(AbapName = "BASE_UOM_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 65, Offset2 = 118)]
        //[XmlElement("BASE_UOM_ISO", Form=XmlSchemaForm.Unqualified)]
        public string Base_Uom_Iso
        {
            get
            {
                return _Base_Uom_Iso;
            }
            set
            {
                _Base_Uom_Iso = value;
            }
        }
        private string _Base_Uom_Iso;


        /// <summary>
        /// Value fields: Quantities
        /// </summary>

        //[RfcField(AbapName = "QUA_VALCOM", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Length2 = 8, Decimals = 3, Offset = 68, Offset2 = 124)]
        //[XmlElement("QUA_VALCOM", Form=XmlSchemaForm.Unqualified)]
        public Decimal Qua_Valcom
        {
            get
            {
                return _Qua_Valcom;
            }
            set
            {
                _Qua_Valcom = value;
            }
        }
        private Decimal _Qua_Valcom;

        public void SetValue(IRfcStructure structure)
        {
            this.Itemno_Acc = structure.GetInt("ITEMNO_ACC").ToString();
            this.Fieldname = structure.GetString("FIELDNAME");
            this.Curr_Type = structure.GetString("CURR_TYPE");
            this.Currency = structure.GetString("CURRENCY");
            this.Currency_Iso = structure.GetString("CURRENCY_ISO");
            this.Amt_Valcom = structure.GetDecimal("AMT_VALCOM");
            this.Base_Uom = structure.GetString("BASE_UOM");
            this.Base_Uom_Iso = structure.GetString("BASE_UOM_ISO");
            this.Qua_Valcom = structure.GetDecimal("QUA_VALCOM");
        }

        public IRfcStructure GetStructure(RfcRepository repository)
        {
            IRfcStructure structure = repository.GetStructureMetadata("BAPIACKEV9").CreateStructure();

            structure.SetValue("ITEMNO_ACC", this.Itemno_Acc);
            structure.SetValue("FIELDNAME", this.Fieldname);
            structure.SetValue("CURR_TYPE", this.Curr_Type);
            structure.SetValue("CURRENCY", this.Currency);
            structure.SetValue("CURRENCY_ISO", this.Currency_Iso);
            structure.SetValue("AMT_VALCOM", Math.Round(this.Amt_Valcom, 4, MidpointRounding.AwayFromZero));
            structure.SetValue("BASE_UOM", this.Base_Uom);
            structure.SetValue("BASE_UOM_ISO", this.Base_Uom_Iso);
            structure.SetValue("QUA_VALCOM", this.Qua_Valcom);

            return structure;
        }
    }

}
