
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2/4/2552
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
//using SAP.Connector;
using SAP.Middleware.Connector;

namespace SCG.eAccounting.SAP.BAPI
{
    /// <summary>
    /// A typed collection of BAPIACCR09 elements.
    /// </summary>
    [Serializable]
    public class BAPIACCR09Table : BAPITable //: SAPTable
    {

        /// <summary>
        /// Returns the element type BAPIACCR09.
        /// </summary>
        /// <returns>The type BAPIACCR09.</returns>
        public override Type GetElementType()
        {
            return (typeof(BAPIACCR09));
        }

        /// <summary>
        /// Creates an empty new row of type BAPIACCR09.
        /// </summary>
        /// <returns>The newBAPIACCR09.</returns>
        public override object CreateNewRow()
        {
            return new BAPIACCR09();
        }

        /// <summary>
        /// The indexer of the collection.
        /// </summary>
        public BAPIACCR09 this[int index]
        {
            get
            {
                return ((BAPIACCR09)(List[index]));
            }
            set
            {
                List[index] = value;
            }
        }

        /// <summary>
        /// Adds a BAPIACCR09 to the end of the collection.
        /// </summary>
        /// <param name="value">The BAPIACCR09 to be added to the end of the collection.</param>
        /// <returns>The index of the newBAPIACCR09.</returns>
        public int Add(BAPIACCR09 value)
        {
            return List.Add(value);
        }

        /// <summary>
        /// Inserts a BAPIACCR09 into the collection at the specified index.
        /// </summary>
        /// <param name="index">The zero-based index at which value should be inserted.</param>
        /// <param name="value">The BAPIACCR09 to insert.</param>
        public void Insert(int index, BAPIACCR09 value)
        {
            List.Insert(index, value);
        }

        /// <summary>
        /// Searches for the specified BAPIACCR09 and returnes the zero-based index of the first occurrence in the collection.
        /// </summary>
        /// <param name="value">The BAPIACCR09 to locate in the collection.</param>
        /// <returns>The index of the object found or -1.</returns>
        public int IndexOf(BAPIACCR09 value)
        {
            return List.IndexOf(value);
        }

        /// <summary>
        /// Determines wheter an element is in the collection.
        /// </summary>
        /// <param name="value">The BAPIACCR09 to locate in the collection.</param>
        /// <returns>True if found; else false.</returns>
        public bool Contains(BAPIACCR09 value)
        {
            return List.Contains(value);
        }

        /// <summary>
        /// Removes the first occurrence of the specified BAPIACCR09 from the collection.
        /// </summary>
        /// <param name="value">The BAPIACCR09 to remove from the collection.</param>
        public void Remove(BAPIACCR09 value)
        {
            List.Remove(value);
        }

        /// <summary>
        /// Copies the contents of the BAPIACCR09Table to the specified one-dimensional array starting at the specified index in the target array.
        /// </summary>
        /// <param name="array">The one-dimensional destination array.</param>           
        /// <param name="index">The zero-based index in array at which copying begins.</param>           
        public void CopyTo(BAPIACCR09[] array, int index)
        {
            List.CopyTo(array, index);
        }

        public void SetValue(IRfcTable table)
        {
            this.Clear();

            for (int i = 0; i < table.RowCount; i++)
            {
                table.CurrentIndex = i;
                BAPIACCR09 dataRow = this.CreateNewRow() as BAPIACCR09;
                dataRow.SetValue(table.CurrentRow);
                this.Add(dataRow);
            }
        }

        public IRfcTable GetTable(RfcRepository repository)
        {
            IRfcTable table = repository.GetTableMetadata("CURRENCYAMOUNT").CreateTable(List.Count);

            for (int i = 0; i < List.Count; i++)
            {
                table.Append(((BAPIACCR09)List[i]).GetStructure(repository));
            }

            return table;
        }

        public IRfcTable GetTable(RfcRepository repository, IRfcTable table)
        {
            for (int i = 0; i < List.Count; i++)
            {
                table.Append(((BAPIACCR09)List[i]).GetStructure(repository));
            }

            return table;
        }
    }
}
