
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2/4/2552
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Middleware.Connector;
//using SAP.Connector;

namespace SCG.eAccounting.SAP.BAPI
{

    /// <summary>
    /// YBAPI_GETFIDOC - Header
    /// </summary>
    //[RfcStructure(AbapName ="YGETFIDOC_H" , Length = 167, Length2 = 334)]
    [Serializable]
    public class YGETFIDOC_H //: SAPStructure
    {


        /// <summary>
        /// Accounting Document Number
        /// </summary>

        //[RfcField(AbapName = "BELNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
        //[XmlElement("BELNR", Form=XmlSchemaForm.Unqualified)]
        public string Belnr
        {
            get
            {
                return _Belnr;
            }
            set
            {
                _Belnr = value;
            }
        }
        private string _Belnr;


        /// <summary>
        /// Company Code
        /// </summary>

        //[RfcField(AbapName = "BUKRS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 10, Offset2 = 20)]
        //[XmlElement("BUKRS", Form=XmlSchemaForm.Unqualified)]
        public string Bukrs
        {
            get
            {
                return _Bukrs;
            }
            set
            {
                _Bukrs = value;
            }
        }
        private string _Bukrs;


        /// <summary>
        /// Posting Date in the Document
        /// </summary>

        //[RfcField(AbapName = "BUDAT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 14, Offset2 = 28)]
        //[XmlElement("BUDAT", Form=XmlSchemaForm.Unqualified)]
        public string Budat
        {
            get
            {
                return _Budat;
            }
            set
            {
                _Budat = value;
            }
        }
        private string _Budat;


        /// <summary>
        /// Reference Document Number
        /// </summary>

        //[RfcField(AbapName = "XBLNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 22, Offset2 = 44)]
        //[XmlElement("XBLNR", Form=XmlSchemaForm.Unqualified)]
        public string Xblnr
        {
            get
            {
                return _Xblnr;
            }
            set
            {
                _Xblnr = value;
            }
        }
        private string _Xblnr;


        /// <summary>
        /// Document Header Text
        /// </summary>

        //[RfcField(AbapName = "BKTXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 25, Length2 = 50, Offset = 38, Offset2 = 76)]
        //[XmlElement("BKTXT", Form=XmlSchemaForm.Unqualified)]
        public string Bktxt
        {
            get
            {
                return _Bktxt;
            }
            set
            {
                _Bktxt = value;
            }
        }
        private string _Bktxt;


        /// <summary>
        /// Bank Branch
        /// </summary>

        //[RfcField(AbapName = "BRNCH", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 63, Offset2 = 126)]
        //[XmlElement("BRNCH", Form=XmlSchemaForm.Unqualified)]
        public string Brnch
        {
            get
            {
                return _Brnch;
            }
            set
            {
                _Brnch = value;
            }
        }
        private string _Brnch;


        /// <summary>
        /// Reverse Document Number
        /// </summary>

        //[RfcField(AbapName = "STBLG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 103, Offset2 = 206)]
        //[XmlElement("STBLG", Form=XmlSchemaForm.Unqualified)]
        public string Stblg
        {
            get
            {
                return _Stblg;
            }
            set
            {
                _Stblg = value;
            }
        }
        private string _Stblg;


        /// <summary>
        /// Name of the company code or company
        /// </summary>

        //[RfcField(AbapName = "BUTXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 25, Length2 = 50, Offset = 113, Offset2 = 226)]
        //[XmlElement("BUTXT", Form=XmlSchemaForm.Unqualified)]
        public string Butxt
        {
            get
            {
                return _Butxt;
            }
            set
            {
                _Butxt = value;
            }
        }
        private string _Butxt;


        /// <summary>
        /// Accounting Document Entry Date
        /// </summary>

        //[RfcField(AbapName = "CPUDT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 138, Offset2 = 276)]
        //[XmlElement("CPUDT", Form=XmlSchemaForm.Unqualified)]
        public string Cpudt
        {
            get
            {
                return _Cpudt;
            }
            set
            {
                _Cpudt = value;
            }
        }
        private string _Cpudt;


        /// <summary>
        /// Time of Entry
        /// </summary>

        //[RfcField(AbapName = "CPUTM", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 146, Offset2 = 292)]
        //[XmlElement("CPUTM", Form=XmlSchemaForm.Unqualified)]
        public string Cputm
        {
            get
            {
                return _Cputm;
            }
            set
            {
                _Cputm = value;
            }
        }
        private string _Cputm;


        /// <summary>
        /// Document Date in Document
        /// </summary>

        //[RfcField(AbapName = "BLDAT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 152, Offset2 = 304)]
        //[XmlElement("BLDAT", Form=XmlSchemaForm.Unqualified)]
        public string Bldat
        {
            get
            {
                return _Bldat;
            }
            set
            {
                _Bldat = value;
            }
        }
        private string _Bldat;


        /// <summary>
        /// Document type
        /// </summary>

        //[RfcField(AbapName = "BLART", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 160, Offset2 = 320)]
        //[XmlElement("BLART", Form=XmlSchemaForm.Unqualified)]
        public string Blart
        {
            get
            {
                return _Blart;
            }
            set
            {
                _Blart = value;
            }
        }
        private string _Blart;


        /// <summary>
        /// Currency Key
        /// </summary>

        //[RfcField(AbapName = "WAERS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 162, Offset2 = 324)]
        //[XmlElement("WAERS", Form=XmlSchemaForm.Unqualified)]
        public string Waers
        {
            get
            {
                return _Waers;
            }
            set
            {
                _Waers = value;
            }
        }
        private string _Waers;

        public void SetValue(IRfcStructure structure)
        {
            this.Belnr = structure.GetString("BELNR");
            this.Bukrs = structure.GetString("BUKRS");
            this.Budat = structure.GetString("BUDAT");
            this.Xblnr = structure.GetString("XBLNR");
            this.Bktxt = structure.GetString("BKTXT");
            this.Brnch = structure.GetString("BRNCH");
            this.Stblg = structure.GetString("STBLG");
            this.Butxt = structure.GetString("BUTXT");
            this.Cpudt = structure.GetString("CPUDT");
            this.Cputm = structure.GetString("CPUTM");
            this.Bldat = structure.GetString("BLDAT");
            this.Blart = structure.GetString("BLART");
            this.Waers = structure.GetString("WAERS");
        }

        public IRfcStructure GetStructure(RfcRepository repository)
        {
            IRfcStructure structure = repository.GetStructureMetadata("YGETFIDOC_H").CreateStructure();

            structure.SetValue("BELNR", this.Belnr);
            structure.SetValue("BUKRS", this.Bukrs);
            structure.SetValue("BUDAT", this.Budat);
            structure.SetValue("XBLNR", this.Xblnr);
            structure.SetValue("BKTXT", this.Bktxt);
            structure.SetValue("BRNCH", this.Brnch);
            structure.SetValue("STBLG", this.Stblg);
            structure.SetValue("BUTXT", this.Butxt);
            structure.SetValue("CPUDT", this.Cpudt);
            structure.SetValue("CPUTM", this.Cputm);
            structure.SetValue("BLDAT", this.Bldat);
            structure.SetValue("BLART", this.Blart);
            structure.SetValue("WAERS", this.Waers);

            return structure;
        }
    }

}
