//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SS.SU.DTO
{
	/// <summary>
	/// POJO for SuEmailResending. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class SuEmailResending
	{
		#region Fields
		
		private long _id;
		private string _emailtype;
		private DateTime _lastsenddate;
		private string _mailcontent;
		private int _retry;
		private string _status;
		private DateTime creDate;
		private long creby;
		private string _sendto;
		private string _subject;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the SuEmailResending class
		/// </summary>
		public SuEmailResending()
		{
		}

		public SuEmailResending(long _id)
		{
			this._id = _id;
		}
	
		/// <summary>
		/// Initializes a new instance of the SuEmailResending class
		/// </summary>
		/// <param name="_emailtype">Initial <see cref="SuEmailResending.emailtype" /> value</param>
		/// <param name="_lastsenddate">Initial <see cref="SuEmailResending.lastsenddate" /> value</param>
		/// <param name="_mailcontent">Initial <see cref="SuEmailResending.mailcontent" /> value</param>
		/// <param name="_retry">Initial <see cref="SuEmailResending.retry" /> value</param>
		/// <param name="_status">Initial <see cref="SuEmailResending.status" /> value</param>
		/// <param name="creDate">Initial <see cref="SuEmailResending.CreDate" /> value</param>
		/// <param name="creby">Initial <see cref="SuEmailResending.Creby" /> value</param>
		/// <param name="_sendto">Initial <see cref="SuEmailResending.sendto" /> value</param>
		/// <param name="_subject">Initial <see cref="SuEmailResending.subject" /> value</param>
		public SuEmailResending(string _emailtype, DateTime _lastsenddate, string _mailcontent, int _retry, string _status, DateTime creDate, long creby, string _sendto, string _subject)
		{
			this._emailtype = _emailtype;
			this._lastsenddate = _lastsenddate;
			this._mailcontent = _mailcontent;
			this._retry = _retry;
			this._status = _status;
			this.creDate = creDate;
			this.creby = creby;
			this._sendto = _sendto;
			this._subject = _subject;
		}
	
		/// <summary>
		/// Minimal constructor for class SuEmailResending
		/// </summary>
		/// <param name="_lastsenddate">Initial <see cref="SuEmailResending.lastsenddate" /> value</param>
		/// <param name="creDate">Initial <see cref="SuEmailResending.CreDate" /> value</param>
		/// <param name="creby">Initial <see cref="SuEmailResending.Creby" /> value</param>
		public SuEmailResending(DateTime _lastsenddate, DateTime creDate, long creby)
		{
			this._lastsenddate = _lastsenddate;
			this.creDate = creDate;
			this.creby = creby;
		}
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the id for the current SuEmailResending
		/// </summary>
		public virtual long id
		{
			get { return this._id; }
			set { this._id = value; }
		}
		
		/// <summary>
		/// Gets or sets the emailtype for the current SuEmailResending
		/// </summary>
		public virtual string emailtype
		{
			get { return this._emailtype; }
			set { this._emailtype = value; }
		}
		
		/// <summary>
		/// Gets or sets the lastsenddate for the current SuEmailResending
		/// </summary>
		public virtual DateTime lastsenddate
		{
			get { return this._lastsenddate; }
			set { this._lastsenddate = value; }
		}
		
		/// <summary>
		/// Gets or sets the mailcontent for the current SuEmailResending
		/// </summary>
		public virtual string mailcontent
		{
			get { return this._mailcontent; }
			set { this._mailcontent = value; }
		}
		
		/// <summary>
		/// Gets or sets the retry for the current SuEmailResending
		/// </summary>
		public virtual int retry
		{
			get { return this._retry; }
			set { this._retry = value; }
		}
		
		/// <summary>
		/// Gets or sets the status for the current SuEmailResending
		/// </summary>
		public virtual string status
		{
			get { return this._status; }
			set { this._status = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current SuEmailResending
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the Creby for the current SuEmailResending
		/// </summary>
		public virtual long Creby
		{
			get { return this.creby; }
			set { this.creby = value; }
		}
		
		/// <summary>
		/// Gets or sets the sendto for the current SuEmailResending
		/// </summary>
		public virtual string sendto
		{
			get { return this._sendto; }
			set { this._sendto = value; }
		}
		
		/// <summary>
		/// Gets or sets the subject for the current SuEmailResending
		/// </summary>
		public virtual string subject
		{
			get { return this._subject; }
			set { this._subject = value; }
		}
		
		#endregion
	}
}
