//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SS.SU.DTO
{
	/// <summary>
	/// POJO for SuProgram. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class SuProgram
	{
		#region Fields
		
		private short programid;
		private string comment;
		private long updBy;
		private DateTime updDate;
		private long creBy;
		private DateTime creDate;
		private string updPgm;
		private Byte[] rowVersion;
		private bool active;
		//private SS.SU.DTO.SuProgram programCode;
        private string programCode;
        private string programPath;
		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the SuProgram class
		/// </summary>
		public SuProgram()
		{
		}

		public SuProgram(short programid)
		{
			this.programid = programid;
		}
	
		/// <summary>
		/// Initializes a new instance of the SuProgram class
		/// </summary>
		/// <param name="comment">Initial <see cref="SuProgram.Comment" /> value</param>
		/// <param name="updBy">Initial <see cref="SuProgram.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="SuProgram.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="SuProgram.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="SuProgram.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="SuProgram.UpdPgm" /> value</param>
		/// <param name="rowVersion">Initial <see cref="SuProgram.RowVersion" /> value</param>
		/// <param name="active">Initial <see cref="SuProgram.Active" /> value</param>
		/// <param name="programCode">Initial <see cref="SuProgram.ProgramCode" /> value</param>
        public SuProgram(string comment, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, Byte[] rowVersion, bool active, string programCode, string programPath)
		{
			this.comment = comment;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.rowVersion = rowVersion;
			this.active = active;
			this.programCode = programCode;
            this.programPath = programPath;
		}
	
		/// <summary>
		/// Minimal constructor for class SuProgram
		/// </summary>
		/// <param name="updBy">Initial <see cref="SuProgram.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="SuProgram.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="SuProgram.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="SuProgram.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="SuProgram.UpdPgm" /> value</param>
		/// <param name="active">Initial <see cref="SuProgram.Active" /> value</param>
		public SuProgram(long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm, bool active)
		{
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
			this.active = active;
		}
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the Programid for the current SuProgram
		/// </summary>
		public virtual short Programid
		{
			get { return this.programid; }
			set { this.programid = value; }
		}
		
		/// <summary>
		/// Gets or sets the Comment for the current SuProgram
		/// </summary>
		public virtual string Comment
		{
			get { return this.comment; }
			set { this.comment = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdBy for the current SuProgram
		/// </summary>
		public virtual long UpdBy
		{
			get { return this.updBy; }
			set { this.updBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdDate for the current SuProgram
		/// </summary>
		public virtual DateTime UpdDate
		{
			get { return this.updDate; }
			set { this.updDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreBy for the current SuProgram
		/// </summary>
		public virtual long CreBy
		{
			get { return this.creBy; }
			set { this.creBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current SuProgram
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdPgm for the current SuProgram
		/// </summary>
		public virtual string UpdPgm
		{
			get { return this.updPgm; }
			set { this.updPgm = value; }
		}
		
		/// <summary>
		/// Gets or sets the RowVersion for the current SuProgram
		/// </summary>
		public virtual Byte[] RowVersion
		{
			get { return this.rowVersion; }
			set { this.rowVersion = value; }
		}
		
		/// <summary>
		/// Gets or sets the Active for the current SuProgram
		/// </summary>
		public virtual bool Active
		{
			get { return this.active; }
			set { this.active = value; }
		}
		
		/// <summary>
		/// Gets or sets the ProgramCode for the current SuProgram
		/// </summary>
        //public virtual SS.SU.DTO.SuProgram ProgramCode
        //{
        //    get { return this.programCode; }
        //    set { this.programCode = value; }
        //}
        public virtual string ProgramCode
        {
            get { return this.programCode; }
            set { this.programCode = value; }
        }

        public virtual string ProgramPath
        {
            get { return this.programPath; }
            set { this.programPath = value; }
        }
		#endregion
	}
}
