//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SCG.eAccounting.SAP.DTO
{
	/// <summary>
	/// POJO for Bapiacextc. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class Bapiacextc
	{
		#region Fields
		
		private long id;
        private long docId;
		private string field1;
		private string field2;
		private string field3;
		private string field4;
		private bool active;
		private long updBy;
		private DateTime updDate;
		private long creBy;
		private DateTime creDate;
		private byte[] rowVersion;
		private string updPgm;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the Bapiacextc class
		/// </summary>
		public Bapiacextc()
		{
		}

		public Bapiacextc(long id)
		{
			this.id = id;
		}
	
		/// <summary>
		/// Initializes a new instance of the Bapiacextc class
		/// </summary>
		/// <param name="docNo">Initial <see cref="Bapiacextc.DocNo" /> value</param>
		/// <param name="field1">Initial <see cref="Bapiacextc.Field1" /> value</param>
		/// <param name="field2">Initial <see cref="Bapiacextc.Field2" /> value</param>
		/// <param name="field3">Initial <see cref="Bapiacextc.Field3" /> value</param>
		/// <param name="field4">Initial <see cref="Bapiacextc.Field4" /> value</param>
		/// <param name="active">Initial <see cref="Bapiacextc.Active" /> value</param>
		/// <param name="updBy">Initial <see cref="Bapiacextc.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="Bapiacextc.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="Bapiacextc.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="Bapiacextc.CreDate" /> value</param>
		/// <param name="rowVersion">Initial <see cref="Bapiacextc.RowVersion" /> value</param>
		/// <param name="updPgm">Initial <see cref="Bapiacextc.UpdPgm" /> value</param>
		public Bapiacextc(long docId, string field1, string field2, string field3, string field4, bool active, long updBy, DateTime updDate, long creBy, DateTime creDate, byte[] rowVersion, string updPgm)
		{
			this.docId = docId;
			this.field1 = field1;
			this.field2 = field2;
			this.field3 = field3;
			this.field4 = field4;
			this.active = active;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.rowVersion = rowVersion;
			this.updPgm = updPgm;
		}
	
		/// <summary>
		/// Minimal constructor for class Bapiacextc
		/// </summary>
		/// <param name="docNo">Initial <see cref="Bapiacextc.DocNo" /> value</param>
		/// <param name="active">Initial <see cref="Bapiacextc.Active" /> value</param>
		/// <param name="updBy">Initial <see cref="Bapiacextc.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="Bapiacextc.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="Bapiacextc.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="Bapiacextc.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="Bapiacextc.UpdPgm" /> value</param>
		public Bapiacextc(long docId, bool active, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm)
		{
			this.docId = docId;
			this.active = active;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
		}
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the Id for the current Bapiacextc
		/// </summary>
		public virtual long Id
		{
			get { return this.id; }
			set { this.id = value; }
		}
		
		/// <summary>
		/// Gets or sets the DocNo for the current Bapiacextc
		/// </summary>
		public virtual long DocId
		{
            get { return this.docId; }
            set { this.docId = value; }
		}
		
		/// <summary>
		/// Gets or sets the Field1 for the current Bapiacextc
		/// </summary>
		public virtual string Field1
		{
			get { return this.field1; }
			set { this.field1 = value; }
		}
		
		/// <summary>
		/// Gets or sets the Field2 for the current Bapiacextc
		/// </summary>
		public virtual string Field2
		{
			get { return this.field2; }
			set { this.field2 = value; }
		}
		
		/// <summary>
		/// Gets or sets the Field3 for the current Bapiacextc
		/// </summary>
		public virtual string Field3
		{
			get { return this.field3; }
			set { this.field3 = value; }
		}
		
		/// <summary>
		/// Gets or sets the Field4 for the current Bapiacextc
		/// </summary>
		public virtual string Field4
		{
			get { return this.field4; }
			set { this.field4 = value; }
		}
		
		/// <summary>
		/// Gets or sets the Active for the current Bapiacextc
		/// </summary>
		public virtual bool Active
		{
			get { return this.active; }
			set { this.active = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdBy for the current Bapiacextc
		/// </summary>
		public virtual long UpdBy
		{
			get { return this.updBy; }
			set { this.updBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdDate for the current Bapiacextc
		/// </summary>
		public virtual DateTime UpdDate
		{
			get { return this.updDate; }
			set { this.updDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreBy for the current Bapiacextc
		/// </summary>
		public virtual long CreBy
		{
			get { return this.creBy; }
			set { this.creBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current Bapiacextc
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the RowVersion for the current Bapiacextc
		/// </summary>
		public virtual byte[] RowVersion
		{
			get { return this.rowVersion; }
			set { this.rowVersion = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdPgm for the current Bapiacextc
		/// </summary>
		public virtual string UpdPgm
		{
			get { return this.updPgm; }
			set { this.updPgm = value; }
		}
		
		#endregion

        private string docSeq;
        public virtual string DocSeq
        {
            get { return this.docSeq; }
            set { this.docSeq = value; }
        }
        private string docKind;
        public virtual string DocKind
        {
            get { return this.docKind; }
            set { this.docKind = value; }
        }
	}
}
