//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SCG.eAccounting.SAP.DTO
{
	/// <summary>
	/// POJO for Bapiaccahd. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class Bapiaccahd
	{
		#region Fields
		
		private long id;
		private string docNo;
		private string docTypeCa;
		private string resKey;
		private string fikey;
		private string paymentFormRef;
		private bool active;
		private long updBy;
		private DateTime updDate;
		private long creBy;
		private DateTime creDate;
		private byte[] rowVersion;
		private string updPgm;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the Bapiaccahd class
		/// </summary>
		public Bapiaccahd()
		{
		}

		public Bapiaccahd(long id)
		{
			this.id = id;
		}
	
		/// <summary>
		/// Initializes a new instance of the Bapiaccahd class
		/// </summary>
		/// <param name="docNo">Initial <see cref="Bapiaccahd.DocNo" /> value</param>
		/// <param name="docTypeCa">Initial <see cref="Bapiaccahd.DocTypeCa" /> value</param>
		/// <param name="resKey">Initial <see cref="Bapiaccahd.ResKey" /> value</param>
		/// <param name="fikey">Initial <see cref="Bapiaccahd.Fikey" /> value</param>
		/// <param name="paymentFormRef">Initial <see cref="Bapiaccahd.PaymentFormRef" /> value</param>
		/// <param name="active">Initial <see cref="Bapiaccahd.Active" /> value</param>
		/// <param name="updBy">Initial <see cref="Bapiaccahd.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="Bapiaccahd.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="Bapiaccahd.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="Bapiaccahd.CreDate" /> value</param>
		/// <param name="rowVersion">Initial <see cref="Bapiaccahd.RowVersion" /> value</param>
		/// <param name="updPgm">Initial <see cref="Bapiaccahd.UpdPgm" /> value</param>
		public Bapiaccahd(string docNo, string docTypeCa, string resKey, string fikey, string paymentFormRef, bool active, long updBy, DateTime updDate, long creBy, DateTime creDate, byte[] rowVersion, string updPgm)
		{
			this.docNo = docNo;
			this.docTypeCa = docTypeCa;
			this.resKey = resKey;
			this.fikey = fikey;
			this.paymentFormRef = paymentFormRef;
			this.active = active;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.rowVersion = rowVersion;
			this.updPgm = updPgm;
		}
	
		/// <summary>
		/// Minimal constructor for class Bapiaccahd
		/// </summary>
		/// <param name="active">Initial <see cref="Bapiaccahd.Active" /> value</param>
		/// <param name="updBy">Initial <see cref="Bapiaccahd.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="Bapiaccahd.UpdDate" /> value</param>
		/// <param name="creBy">Initial <see cref="Bapiaccahd.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="Bapiaccahd.CreDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="Bapiaccahd.UpdPgm" /> value</param>
		public Bapiaccahd(bool active, long updBy, DateTime updDate, long creBy, DateTime creDate, string updPgm)
		{
			this.active = active;
			this.updBy = updBy;
			this.updDate = updDate;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updPgm = updPgm;
		}
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the Id for the current Bapiaccahd
		/// </summary>
		public virtual long Id
		{
			get { return this.id; }
			set { this.id = value; }
		}
		
		/// <summary>
		/// Gets or sets the DocNo for the current Bapiaccahd
		/// </summary>
		public virtual string DocNo
		{
			get { return this.docNo; }
			set { this.docNo = value; }
		}
		
		/// <summary>
		/// Gets or sets the DocTypeCa for the current Bapiaccahd
		/// </summary>
		public virtual string DocTypeCa
		{
			get { return this.docTypeCa; }
			set { this.docTypeCa = value; }
		}
		
		/// <summary>
		/// Gets or sets the ResKey for the current Bapiaccahd
		/// </summary>
		public virtual string ResKey
		{
			get { return this.resKey; }
			set { this.resKey = value; }
		}
		
		/// <summary>
		/// Gets or sets the Fikey for the current Bapiaccahd
		/// </summary>
		public virtual string Fikey
		{
			get { return this.fikey; }
			set { this.fikey = value; }
		}
		
		/// <summary>
		/// Gets or sets the PaymentFormRef for the current Bapiaccahd
		/// </summary>
		public virtual string PaymentFormRef
		{
			get { return this.paymentFormRef; }
			set { this.paymentFormRef = value; }
		}
		
		/// <summary>
		/// Gets or sets the Active for the current Bapiaccahd
		/// </summary>
		public virtual bool Active
		{
			get { return this.active; }
			set { this.active = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdBy for the current Bapiaccahd
		/// </summary>
		public virtual long UpdBy
		{
			get { return this.updBy; }
			set { this.updBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdDate for the current Bapiaccahd
		/// </summary>
		public virtual DateTime UpdDate
		{
			get { return this.updDate; }
			set { this.updDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreBy for the current Bapiaccahd
		/// </summary>
		public virtual long CreBy
		{
			get { return this.creBy; }
			set { this.creBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current Bapiaccahd
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the RowVersion for the current Bapiaccahd
		/// </summary>
		public virtual byte[] RowVersion
		{
			get { return this.rowVersion; }
			set { this.rowVersion = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdPgm for the current Bapiaccahd
		/// </summary>
		public virtual string UpdPgm
		{
			get { return this.updPgm; }
			set { this.updPgm = value; }
		}
		
		#endregion
	}
}
