<html>
<head>
    <title>Untitled Page</title>
</head>

<style type="text/css">
.fontA {
    font-family:Tahoma;
	font-size:14px;
}
.HeaderTable{
	font-weight:bold;
	background-color:#1d9f34;
	color:White;
	text-align:center;
}
.ItemTable{
	background-color:#a4f4a0;
	color:#2D2D2D;
}
</style>

 <BODY class="fontA">

<div aling="LEFT">
<IMG SRC="$link$/App_Themes/Default/images/email/head.png" BORDER="0" ALT="SCG Account">
</div>

<p> <B>Dear Khun $receiverName$ </B></p>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This e-mail has been sent to notify that Corporate Account has not received your original supporting 
 documents for <br/> the request form no <b>$requestID$</b> Subject <b><font color='red'>$subject$</font></b> This document has been approved verification <br/> by 
 accountant for <b><font color='red'>$numberdate$</font></b> days ago.
<br/><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;According to company’s regulations and legal requirements, please kindly submit your documents to 
Employee Expense Processing (EMP) <br/> to complete this request for you  
<br/>
<p>$comment$</p>
<br/>
Please click link <b><a href="$link$/Login.aspx?wfid=$wfid$">here</a></b> for more details. 
<br/>
<br/>
<p>$noteEN$</p>
<br/>
<br/>
<b>Yours Sincerely,<br/>
Administrator e-Xpense</b>
<br/>
<br/>
<div aling="LEFT">
<IMG SRC="$link$/App_Themes/Default/images/email/LINE.png" BORDER="0" ALT="SCG Account">
</div>

<p> <B>เรียน คุณ$receiverName$</B></p>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;อีเมล์ฉบับนี้ส่งมาเพื่อแจ้งเตือนว่า ทางเอสซีจี แอคเค้าน์ติ้ง   ยังไม่ได้รับต้นฉบับเอกสารประกอบ สำหรับใบขอเบิกค่าใช้จ่าย
<br/> เลขที่  <b>$requestID$</b> เรื่อง  <b><font color='red'>$subject$</font></b>  ซึ่งเอกสารดังกล่าวผ่านการอนุมัติตรวจจ่ายและบันทึกบัญชีแล้ว   <b><font color='red'>$numberdate$</font></b> วัน
<br/><br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   กรุณาส่งต้นฉบับเอกสารดังกล่าว ถึงหน่วยงาน Employee Expense Processing  (EMP) เพื่อให้เอกสารสมบูรณ์ถูกต้อง
ตามระเบียบบริษัทฯ <br/> และข้อกำหนดทางกฎหมายด้วย
<br/>
<p>$comment$</p>
<br/>
โปรดคลิกลิ้งค์ <b><a href="$link$/Login.aspx?wfid=$wfid$">ที่นี้</a></b> เพื่อดูรายละเอียดเพิ่มเติม
<br/>
<br/>
<p>$noteTH$</p>
<br/>
<br/>
<b>ขอแสดงความนับถือ<br/>
Administrator e-Xpense</b>
<br/>
<br/>
<div aling="LEFT">
<IMG SRC="$link$/App_Themes/Default/images/email/LINE.png" BORDER="0" ALT="SCG Account">
</div>
<br/>
   This service was provided by Employee Expense Services - P2P (Purchase to Pay Process), CAD ,Siam Cement Public Co.,Ltd.
   <br/>
Your comments and suggestions are welcome. Please contact us at 
<a href="mailto:myempadm@scg.co.th">myempadm@scg.co.th</a>
<br/>
<br/>
<div aling="LEFT">
<IMG SRC="$link$/App_Themes/Default/images/email/foolter.png" BORDER="0" ALT="SCG Account">
</div>

</body>
</html>