//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.eAccounting.DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.24.0.46\\SQL2012;Initial Catalog=eXpense;Persist Security Info=Tru" +
            "e;User ID=sa;Password=p@ssw0rd")]
        public string eXpenseConnectionString {
            get {
                return ((string)(this["eXpenseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HQSQLSVR\\SCG;Initial Catalog=eAccounting-SCGPrd;Persist Security Info" +
            "=True;User ID=sa")]
        public string eAccounting_SCGPrdConnectionString {
            get {
                return ((string)(this["eAccounting_SCGPrdConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HQSQLSVR\\SCG;Initial Catalog=eXpense2011;Persist Security Info=True;U" +
            "ser ID=sa;Password=sa@SCG")]
        public string eAccountingConnectionString {
            get {
                return ((string)(this["eAccountingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HQSQLSVR\\SCG;Initial Catalog=eXpense2011;Persist Security Info=True;U" +
            "ser ID=sa;Password=sa@SCG")]
        public string eXpense2011ConnectionString {
            get {
                return ((string)(this["eXpense2011ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.24.0.46\\SQL2012;Initial Catalog=eXpenseECC;User ID=sa;Password=p@" +
            "ssw0rd")]
        public string eXpenseECCConnectionString {
            get {
                return ((string)(this["eXpenseECCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FSDBSVR3\\SQL2012;Initial Catalog=expenseECC;User ID=sa;Password=p@ssw" +
            "0rd")]
        public string expenseECCConnectionString1 {
            get {
                return ((string)(this["expenseECCConnectionString1"]));
            }
        }
    }
}
