//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace SCG.eAccounting.DTO
{
	/// <summary>
	/// POJO for FneacAdvanceImportTemp. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class FneacAdvanceImportTemp
	{
		#region Fields
		
		private long tempID;
		private string expenseNo;
		private string expenseComCode;
		private DateTime? expenseCreateDate;
		private string requesterUserCode;
		private string receiverUserCode;
		private double netAmount;
		private string paymentType;
		private DateTime? clearAdvanceDate;
		private DateTime? clearAdvanceDueDate;
		private string approveUserCode;
		private long expenseComID;
		private long requesterUserID;
		private long receiverUserID;
		private long approveUserID;
		private long pBID;
		private string pBCode;
		private string subject;
		private string reasonDue;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the FneacAdvanceImportTemp class
		/// </summary>
		public FneacAdvanceImportTemp()
		{
		}

		public FneacAdvanceImportTemp(long tempID)
		{
			this.tempID = tempID;
		}
	
		/// <summary>
		/// Initializes a new instance of the FneacAdvanceImportTemp class
		/// </summary>
		/// <param name="expenseNo">Initial <see cref="FneacAdvanceImportTemp.ExpenseNo" /> value</param>
		/// <param name="expenseComCode">Initial <see cref="FneacAdvanceImportTemp.ExpenseComCode" /> value</param>
		/// <param name="expenseCreateDate">Initial <see cref="FneacAdvanceImportTemp.ExpenseCreateDate" /> value</param>
		/// <param name="requesterUserCode">Initial <see cref="FneacAdvanceImportTemp.RequesterUserCode" /> value</param>
		/// <param name="receiverUserCode">Initial <see cref="FneacAdvanceImportTemp.ReceiverUserCode" /> value</param>
		/// <param name="netAmount">Initial <see cref="FneacAdvanceImportTemp.NetAmount" /> value</param>
		/// <param name="paymentType">Initial <see cref="FneacAdvanceImportTemp.PaymentType" /> value</param>
		/// <param name="clearAdvanceDate">Initial <see cref="FneacAdvanceImportTemp.ClearAdvanceDate" /> value</param>
		/// <param name="clearAdvanceDueDate">Initial <see cref="FneacAdvanceImportTemp.ClearAdvanceDueDate" /> value</param>
		/// <param name="approveUserCode">Initial <see cref="FneacAdvanceImportTemp.ApproveUserCode" /> value</param>
		/// <param name="expenseComID">Initial <see cref="FneacAdvanceImportTemp.ExpenseComID" /> value</param>
		/// <param name="requesterUserID">Initial <see cref="FneacAdvanceImportTemp.RequesterUserID" /> value</param>
		/// <param name="receiverUserID">Initial <see cref="FneacAdvanceImportTemp.ReceiverUserID" /> value</param>
		/// <param name="approveUserID">Initial <see cref="FneacAdvanceImportTemp.ApproveUserID" /> value</param>
		/// <param name="pBID">Initial <see cref="FneacAdvanceImportTemp.PBID" /> value</param>
		/// <param name="pBCode">Initial <see cref="FneacAdvanceImportTemp.PBCode" /> value</param>
		/// <param name="subject">Initial <see cref="FneacAdvanceImportTemp.Subject" /> value</param>
		/// <param name="reasonDue">Initial <see cref="FneacAdvanceImportTemp.ReasonDue" /> value</param>
		public FneacAdvanceImportTemp(string expenseNo, string expenseComCode, DateTime? expenseCreateDate, string requesterUserCode, string receiverUserCode, double netAmount, string paymentType, DateTime? clearAdvanceDate, DateTime? clearAdvanceDueDate, string approveUserCode, long expenseComID, long requesterUserID, long receiverUserID, long approveUserID, long pBID, string pBCode, string subject, string reasonDue)
		{
			this.expenseNo = expenseNo;
			this.expenseComCode = expenseComCode;
			this.expenseCreateDate = expenseCreateDate;
			this.requesterUserCode = requesterUserCode;
			this.receiverUserCode = receiverUserCode;
			this.netAmount = netAmount;
			this.paymentType = paymentType;
			this.clearAdvanceDate = clearAdvanceDate;
			this.clearAdvanceDueDate = clearAdvanceDueDate;
			this.approveUserCode = approveUserCode;
			this.expenseComID = expenseComID;
			this.requesterUserID = requesterUserID;
			this.receiverUserID = receiverUserID;
			this.approveUserID = approveUserID;
			this.pBID = pBID;
			this.pBCode = pBCode;
			this.subject = subject;
			this.reasonDue = reasonDue;
		}
	
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the TempID for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual long TempID
		{
			get { return this.tempID; }
			set { this.tempID = value; }
		}
		
		/// <summary>
		/// Gets or sets the ExpenseNo for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string ExpenseNo
		{
			get { return this.expenseNo; }
			set { this.expenseNo = value; }
		}
		
		/// <summary>
		/// Gets or sets the ExpenseComCode for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string ExpenseComCode
		{
			get { return this.expenseComCode; }
			set { this.expenseComCode = value; }
		}
		
		/// <summary>
		/// Gets or sets the ExpenseCreateDate for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual DateTime? ExpenseCreateDate
		{
			get { return this.expenseCreateDate; }
			set { this.expenseCreateDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the RequesterUserCode for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string RequesterUserCode
		{
			get { return this.requesterUserCode; }
			set { this.requesterUserCode = value; }
		}
		
		/// <summary>
		/// Gets or sets the ReceiverUserCode for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string ReceiverUserCode
		{
			get { return this.receiverUserCode; }
			set { this.receiverUserCode = value; }
		}
		
		/// <summary>
		/// Gets or sets the NetAmount for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual double NetAmount
		{
			get { return this.netAmount; }
			set { this.netAmount = value; }
		}
		
		/// <summary>
		/// Gets or sets the PaymentType for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string PaymentType
		{
			get { return this.paymentType; }
			set { this.paymentType = value; }
		}
		
		/// <summary>
		/// Gets or sets the ClearAdvanceDate for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual DateTime? ClearAdvanceDate
		{
			get { return this.clearAdvanceDate; }
			set { this.clearAdvanceDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the ClearAdvanceDueDate for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual DateTime? ClearAdvanceDueDate
		{
			get { return this.clearAdvanceDueDate; }
			set { this.clearAdvanceDueDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the ApproveUserCode for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string ApproveUserCode
		{
			get { return this.approveUserCode; }
			set { this.approveUserCode = value; }
		}
		
		/// <summary>
		/// Gets or sets the ExpenseComID for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual long ExpenseComID
		{
			get { return this.expenseComID; }
			set { this.expenseComID = value; }
		}
		
		/// <summary>
		/// Gets or sets the RequesterUserID for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual long RequesterUserID
		{
			get { return this.requesterUserID; }
			set { this.requesterUserID = value; }
		}
		
		/// <summary>
		/// Gets or sets the ReceiverUserID for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual long ReceiverUserID
		{
			get { return this.receiverUserID; }
			set { this.receiverUserID = value; }
		}
		
		/// <summary>
		/// Gets or sets the ApproveUserID for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual long ApproveUserID
		{
			get { return this.approveUserID; }
			set { this.approveUserID = value; }
		}
		
		/// <summary>
		/// Gets or sets the PBID for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual long PBID
		{
			get { return this.pBID; }
			set { this.pBID = value; }
		}
		
		/// <summary>
		/// Gets or sets the PBCode for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string PBCode
		{
			get { return this.pBCode; }
			set { this.pBCode = value; }
		}
		
		/// <summary>
		/// Gets or sets the Subject for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string Subject
		{
			get { return this.subject; }
			set { this.subject = value; }
		}
		
		/// <summary>
		/// Gets or sets the ReasonDue for the current FneacAdvanceImportTemp
		/// </summary>
		public virtual string ReasonDue
		{
			get { return this.reasonDue; }
			set { this.reasonDue = value; }
		}
		
		#endregion
	}
}
