//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using SS.Standard.Data.NHibernate.DTO;

namespace SCG.eAccounting.DTO
{
    /// <summary>
    /// POJO for FnExpensePerdiem. This class is autogenerated
    /// </summary>
    [Serializable]
    public partial class FnExpensePerdiem : INHibernateAdapterDTO<long>
    {
        #region Fields

        private long expensePerdiemID;
        private string description;
        private double? perdiemRateUSD;
        private double? perdiemRateUSDHigh;
        private double totalFullDayPerdiem;
        private double fullDayPerdiemRate;
        private double totalFullDayPerdiemAmount;
        private double totalHalfDayPerdiem;
        private double halfDayPerdiemRate;
        private double totalHalfDayPerdiemAmount;
        private double totalFullDayPerdiemHigh;
        private double fullDayPerdiemRateHigh;
        private double totalFullDayPerdiemAmountHigh;
        private double totalHalfDayPerdiemHigh;
        private double halfDayPerdiemRateHigh;
        private double totalHalfDayPerdiemAmountHigh;
        private double perdiemGov;
        private double perdiemGovHigh;
        private double perdiemGovernmentAmount;
        private double perdiemPrivateAmount;
        private double perdiemTotalAmount;
        private double perdiemTaxAmount;
        private double exchangeRate;
        private bool active;
        private long creBy;
        private DateTime creDate;
        private long updBy;
        private DateTime updDate;
        private string updPgm;
        private Byte[] rowVersion;
        private SCG.eAccounting.DTO.FnExpenseDocument expense;
        private SCG.eAccounting.DTO.FnExpenseInvoice invoice;
        private SCG.DB.DTO.DbCostCenter costCenter;
        private SCG.DB.DTO.DbAccount account;
        private SCG.DB.DTO.DbInternalOrder iO;
        private string referenceNo;
        private string saleOrder;
        private string saleItem;
        private double perdiemRate;
        private double perdiemTotalAmountHigh;
        private double perdiemTotalAmountLocalCurrency;
        private double perdiemTotalAmountMainCurrency;

        private double perdiemRateUSDThaiZone;
        private double perdiemTotalAmountThaiZone;
        private double totalFullDayPerdiemThaiZone;
        private double fullDayPerdiemRateThaiZone;
        private double totalFullDayPerdiemAmountThaiZone;
        private double totalHalfDayPerdiemThaiZone;
        private double halfDayPerdiemRateThaiZone;
        private double totalHalfDayPerdiemAmountThaiZone;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the FnExpensePerdiem class
        /// </summary>
        public FnExpensePerdiem()
        {
        }

        public FnExpensePerdiem(long expensePerdiemID)
        {
            this.expensePerdiemID = expensePerdiemID;
        }

        /// <summary>
        /// Initializes a new instance of the FnExpensePerdiem class
        /// </summary>
        /// <param name="description">Initial <see cref="FnExpensePerdiem.Description" /> value</param>
        /// <param name="perdiemRateUSD">Initial <see cref="FnExpensePerdiem.PerdiemRateUSD" /> value</param>
        /// <param name="perdiemRateUSDHigh">Initial <see cref="FnExpensePerdiem.PerdiemRateUSDHigh" /> value</param>
        /// <param name="totalFullDayPerdiem">Initial <see cref="FnExpensePerdiem.TotalFullDayPerdiem" /> value</param>
        /// <param name="fullDayPerdiemRate">Initial <see cref="FnExpensePerdiem.FullDayPerdiemRate" /> value</param>
        /// <param name="totalFullDayPerdiemAmount">Initial <see cref="FnExpensePerdiem.TotalFullDayPerdiemAmount" /> value</param>
        /// <param name="totalHalfDayPerdiem">Initial <see cref="FnExpensePerdiem.TotalHalfDayPerdiem" /> value</param>
        /// <param name="halfDayPerdiemRate">Initial <see cref="FnExpensePerdiem.HalfDayPerdiemRate" /> value</param>
        /// <param name="totalHalfDayPerdiemAmount">Initial <see cref="FnExpensePerdiem.TotalHalfDayPerdiemAmount" /> value</param>
        /// <param name="totalFullDayPerdiemHigh">Initial <see cref="FnExpensePerdiem.TotalFullDayPerdiemHigh" /> value</param>
        /// <param name="fullDayPerdiemRateHigh">Initial <see cref="FnExpensePerdiem.FullDayPerdiemRateHigh" /> value</param>
        /// <param name="totalFullDayPerdiemAmountHigh">Initial <see cref="FnExpensePerdiem.TotalFullDayPerdiemAmountHigh" /> value</param>
        /// <param name="totalHalfDayPerdiemHigh">Initial <see cref="FnExpensePerdiem.TotalHalfDayPerdiemHigh" /> value</param>
        /// <param name="halfDayPerdiemRateHigh">Initial <see cref="FnExpensePerdiem.HalfDayPerdiemRateHigh" /> value</param>
        /// <param name="totalHalfDayPerdiemAmountHigh">Initial <see cref="FnExpensePerdiem.TotalHalfDayPerdiemAmountHigh" /> value</param>
        /// <param name="perdiemGov">Initial <see cref="FnExpensePerdiem.PerdiemGov" /> value</param>
        /// <param name="perdiemGovHigh">Initial <see cref="FnExpensePerdiem.PerdiemGovHigh" /> value</param>
        /// <param name="perdiemGovernmentAmount">Initial <see cref="FnExpensePerdiem.PerdiemGovernmentAmount" /> value</param>
        /// <param name="perdiemPrivateAmount">Initial <see cref="FnExpensePerdiem.PerdiemPrivateAmount" /> value</param>
        /// <param name="perdiemTotalAmount">Initial <see cref="FnExpensePerdiem.PerdiemTotalAmount" /> value</param>
        /// <param name="perdiemTaxAmount">Initial <see cref="FnExpensePerdiem.PerdiemTaxAmount" /> value</param>
        /// <param name="active">Initial <see cref="FnExpensePerdiem.Active" /> value</param>
        /// <param name="creBy">Initial <see cref="FnExpensePerdiem.CreBy" /> value</param>
        /// <param name="creDate">Initial <see cref="FnExpensePerdiem.CreDate" /> value</param>
        /// <param name="updBy">Initial <see cref="FnExpensePerdiem.UpdBy" /> value</param>
        /// <param name="updDate">Initial <see cref="FnExpensePerdiem.UpdDate" /> value</param>
        /// <param name="updPgm">Initial <see cref="FnExpensePerdiem.UpdPgm" /> value</param>
        /// <param name="rowVersion">Initial <see cref="FnExpensePerdiem.RowVersion" /> value</param>
        /// <param name="expense">Initial <see cref="FnExpensePerdiem.Expense" /> value</param>
        public FnExpensePerdiem(string description, double? perdiemRateUSD, double? perdiemRateUSDHigh, double totalFullDayPerdiem, double fullDayPerdiemRate, double totalFullDayPerdiemAmount, double totalHalfDayPerdiem, double halfDayPerdiemRate, double totalHalfDayPerdiemAmount, double totalFullDayPerdiemHigh, double fullDayPerdiemRateHigh, double totalFullDayPerdiemAmountHigh, double totalHalfDayPerdiemHigh, double halfDayPerdiemRateHigh, double totalHalfDayPerdiemAmountHigh, double perdiemGov, double perdiemGovHigh, double perdiemGovernmentAmount, double perdiemPrivateAmount, double perdiemTotalAmount, double perdiemTaxAmount, bool active, long creBy, DateTime creDate, long updBy, DateTime updDate, string updPgm, Byte[] rowVersion, SCG.eAccounting.DTO.FnExpenseDocument expense, SCG.DB.DTO.DbCostCenter costCenter, SCG.DB.DTO.DbAccount account, SCG.DB.DTO.DbInternalOrder iO, SCG.eAccounting.DTO.FnExpenseInvoice invoice, string referenceNo, string saleOrder, string saleItem, double perdiemRate, double perdiemTotalAmountHigh, double perdiemTotalAmountLocalCurrency, double perdiemTotalAmountMainCurrency, double perdiemRateUSDThaiZone, double perdiemTotalAmountThaiZone, double totalFullDayPerdiemThaiZone, double fullDayPerdiemRateThaiZone, double totalFullDayPerdiemAmountThaiZone, double totalHalfDayPerdiemThaiZone, double halfDayPerdiemRateThaiZone, double totalHalfDayPerdiemAmountThaiZone)
        {
            this.description = description;
            this.perdiemRateUSD = perdiemRateUSD;
            this.perdiemRateUSDHigh = perdiemRateUSDHigh;
            this.totalFullDayPerdiem = totalFullDayPerdiem;
            this.fullDayPerdiemRate = fullDayPerdiemRate;
            this.totalFullDayPerdiemAmount = totalFullDayPerdiemAmount;
            this.totalHalfDayPerdiem = totalHalfDayPerdiem;
            this.halfDayPerdiemRate = halfDayPerdiemRate;
            this.totalHalfDayPerdiemAmount = totalHalfDayPerdiemAmount;
            this.totalFullDayPerdiemHigh = totalFullDayPerdiemHigh;
            this.fullDayPerdiemRateHigh = fullDayPerdiemRateHigh;
            this.totalFullDayPerdiemAmountHigh = totalFullDayPerdiemAmountHigh;
            this.totalHalfDayPerdiemHigh = totalHalfDayPerdiemHigh;
            this.halfDayPerdiemRateHigh = halfDayPerdiemRateHigh;
            this.totalHalfDayPerdiemAmountHigh = totalHalfDayPerdiemAmountHigh;
            this.perdiemGov = perdiemGov;
            this.perdiemGovHigh = perdiemGovHigh;
            this.perdiemGovernmentAmount = perdiemGovernmentAmount;
            this.perdiemPrivateAmount = perdiemPrivateAmount;
            this.perdiemTotalAmount = perdiemTotalAmount;
            this.perdiemTaxAmount = perdiemTaxAmount;
            this.active = active;
            this.creBy = creBy;
            this.creDate = creDate;
            this.updBy = updBy;
            this.updDate = updDate;
            this.updPgm = updPgm;
            this.rowVersion = rowVersion;
            this.expense = expense;
            this.invoice = invoice;
            this.costCenter = costCenter;
            this.account = account;
            this.iO = iO;
            this.saleOrder = saleOrder;
            this.saleItem = saleItem;
            this.referenceNo = referenceNo;
            this.perdiemRate = perdiemRate;
            this.perdiemTotalAmountHigh = perdiemTotalAmountHigh;
            this.perdiemTotalAmountLocalCurrency = perdiemTotalAmountLocalCurrency;
            this.perdiemTotalAmountMainCurrency = perdiemTotalAmountMainCurrency;
            this.perdiemRateUSDThaiZone = perdiemRateUSDThaiZone;
            this.perdiemTotalAmountThaiZone = perdiemTotalAmountThaiZone;
            this.totalFullDayPerdiemThaiZone = totalFullDayPerdiemThaiZone;
            this.fullDayPerdiemRateThaiZone = fullDayPerdiemRateThaiZone;
            this.totalFullDayPerdiemAmountThaiZone = totalFullDayPerdiemAmountThaiZone;
            this.totalHalfDayPerdiemThaiZone = totalHalfDayPerdiemThaiZone;
            this.halfDayPerdiemRateThaiZone = halfDayPerdiemRateThaiZone;
            this.totalHalfDayPerdiemAmountThaiZone = totalHalfDayPerdiemAmountThaiZone;
        }

        /// <summary>
        /// Minimal constructor for class FnExpensePerdiem
        /// </summary>
        /// <param name="description">Initial <see cref="FnExpensePerdiem.Description" /> value</param>
        /// <param name="active">Initial <see cref="FnExpensePerdiem.Active" /> value</param>
        /// <param name="creBy">Initial <see cref="FnExpensePerdiem.CreBy" /> value</param>
        /// <param name="creDate">Initial <see cref="FnExpensePerdiem.CreDate" /> value</param>
        /// <param name="updBy">Initial <see cref="FnExpensePerdiem.UpdBy" /> value</param>
        /// <param name="updDate">Initial <see cref="FnExpensePerdiem.UpdDate" /> value</param>
        /// <param name="updPgm">Initial <see cref="FnExpensePerdiem.UpdPgm" /> value</param>
        public FnExpensePerdiem(string description, bool active, long creBy, DateTime creDate, long updBy, DateTime updDate, string updPgm)
        {
            this.description = description;
            this.active = active;
            this.creBy = creBy;
            this.creDate = creDate;
            this.updBy = updBy;
            this.updDate = updDate;
            this.updPgm = updPgm;
        }
        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the ExpensePerdiemID for the current FnExpensePerdiem
        /// </summary>
        public virtual long ExpensePerdiemID
        {
            get { return this.expensePerdiemID; }
            set { this.expensePerdiemID = value; }
        }

        /// <summary>
        /// Gets or sets the Description for the current FnExpensePerdiem
        /// </summary>
        public virtual string Description
        {
            get { return this.description; }
            set { this.description = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemRateUSD for the current FnExpensePerdiem
        /// </summary>
        public virtual double? PerdiemRateUSD
        {
            get { return this.perdiemRateUSD; }
            set { this.perdiemRateUSD = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemRateUSDHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double? PerdiemRateUSDHigh
        {
            get { return this.perdiemRateUSDHigh; }
            set { this.perdiemRateUSDHigh = value; }
        }

        /// <summary>
        /// Gets or sets the TotalFullDayPerdiem for the current FnExpensePerdiem
        /// </summary>
        public virtual double TotalFullDayPerdiem
        {
            get { return this.totalFullDayPerdiem; }
            set { this.totalFullDayPerdiem = value; }
        }

        /// <summary>
        /// Gets or sets the FullDayPerdiemRate for the current FnExpensePerdiem
        /// </summary>
        public virtual double FullDayPerdiemRate
        {
            get { return this.fullDayPerdiemRate; }
            set { this.fullDayPerdiemRate = value; }
        }

        /// <summary>
        /// Gets or sets the TotalFullDayPerdiemAmount for the current FnExpensePerdiem
        /// </summary>
        public virtual double TotalFullDayPerdiemAmount
        {
            get { return this.totalFullDayPerdiemAmount; }
            set { this.totalFullDayPerdiemAmount = value; }
        }

        /// <summary>
        /// Gets or sets the TotalHalfDayPerdiem for the current FnExpensePerdiem
        /// </summary>
        public virtual double TotalHalfDayPerdiem
        {
            get { return this.totalHalfDayPerdiem; }
            set { this.totalHalfDayPerdiem = value; }
        }

        /// <summary>
        /// Gets or sets the HalfDayPerdiemRate for the current FnExpensePerdiem
        /// </summary>
        public virtual double HalfDayPerdiemRate
        {
            get { return this.halfDayPerdiemRate; }
            set { this.halfDayPerdiemRate = value; }
        }

        /// <summary>
        /// Gets or sets the TotalHalfDayPerdiemAmount for the current FnExpensePerdiem
        /// </summary>
        public virtual double TotalHalfDayPerdiemAmount
        {
            get { return this.totalHalfDayPerdiemAmount; }
            set { this.totalHalfDayPerdiemAmount = value; }
        }

        /// <summary>
        /// Gets or sets the TotalFullDayPerdiemHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double TotalFullDayPerdiemHigh
        {
            get { return this.totalFullDayPerdiemHigh; }
            set { this.totalFullDayPerdiemHigh = value; }
        }

        /// <summary>
        /// Gets or sets the FullDayPerdiemRateHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double FullDayPerdiemRateHigh
        {
            get { return this.fullDayPerdiemRateHigh; }
            set { this.fullDayPerdiemRateHigh = value; }
        }

        /// <summary>
        /// Gets or sets the TotalFullDayPerdiemAmountHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double TotalFullDayPerdiemAmountHigh
        {
            get { return this.totalFullDayPerdiemAmountHigh; }
            set { this.totalFullDayPerdiemAmountHigh = value; }
        }

        /// <summary>
        /// Gets or sets the TotalHalfDayPerdiemHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double TotalHalfDayPerdiemHigh
        {
            get { return this.totalHalfDayPerdiemHigh; }
            set { this.totalHalfDayPerdiemHigh = value; }
        }

        /// <summary>
        /// Gets or sets the HalfDayPerdiemRateHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double HalfDayPerdiemRateHigh
        {
            get { return this.halfDayPerdiemRateHigh; }
            set { this.halfDayPerdiemRateHigh = value; }
        }

        /// <summary>
        /// Gets or sets the TotalHalfDayPerdiemAmountHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double TotalHalfDayPerdiemAmountHigh
        {
            get { return this.totalHalfDayPerdiemAmountHigh; }
            set { this.totalHalfDayPerdiemAmountHigh = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemGov for the current FnExpensePerdiem
        /// </summary>
        public virtual double PerdiemRateGov
        {
            get { return this.perdiemGov; }
            set { this.perdiemGov = value; }
        }

        public virtual double ExchangeRate
        {
            get { return this.exchangeRate; }
            set { this.exchangeRate = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemGovHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double PerdiemRateGovHigh
        {
            get { return this.perdiemGovHigh; }
            set { this.perdiemGovHigh = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemGovernmentAmount for the current FnExpensePerdiem
        /// </summary>
        public virtual double PerdiemGovernmentAmount
        {
            get { return this.perdiemGovernmentAmount; }
            set { this.perdiemGovernmentAmount = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemPrivateAmount for the current FnExpensePerdiem
        /// </summary>
        public virtual double PerdiemPrivateAmount
        {
            get { return this.perdiemPrivateAmount; }
            set { this.perdiemPrivateAmount = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemTotalAmount for the current FnExpensePerdiem
        /// </summary>
        public virtual double PerdiemTotalAmount
        {
            get { return this.perdiemTotalAmount; }
            set { this.perdiemTotalAmount = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemTaxAmount for the current FnExpensePerdiem
        /// </summary>
        public virtual double PerdiemTaxAmount
        {
            get { return this.perdiemTaxAmount; }
            set { this.perdiemTaxAmount = value; }
        }

        /// <summary>
        /// Gets or sets the Active for the current FnExpensePerdiem
        /// </summary>
        public virtual bool Active
        {
            get { return this.active; }
            set { this.active = value; }
        }

        /// <summary>
        /// Gets or sets the CreBy for the current FnExpensePerdiem
        /// </summary>
        public virtual long CreBy
        {
            get { return this.creBy; }
            set { this.creBy = value; }
        }

        /// <summary>
        /// Gets or sets the CreDate for the current FnExpensePerdiem
        /// </summary>
        public virtual DateTime CreDate
        {
            get { return this.creDate; }
            set { this.creDate = value; }
        }

        /// <summary>
        /// Gets or sets the UpdBy for the current FnExpensePerdiem
        /// </summary>
        public virtual long UpdBy
        {
            get { return this.updBy; }
            set { this.updBy = value; }
        }

        /// <summary>
        /// Gets or sets the UpdDate for the current FnExpensePerdiem
        /// </summary>
        public virtual DateTime UpdDate
        {
            get { return this.updDate; }
            set { this.updDate = value; }
        }

        /// <summary>
        /// Gets or sets the UpdPgm for the current FnExpensePerdiem
        /// </summary>
        public virtual string UpdPgm
        {
            get { return this.updPgm; }
            set { this.updPgm = value; }
        }

        /// <summary>
        /// Gets or sets the RowVersion for the current FnExpensePerdiem
        /// </summary>
        public virtual Byte[] RowVersion
        {
            get { return this.rowVersion; }
            set { this.rowVersion = value; }
        }

        /// <summary>
        /// Gets or sets the Expense for the current FnExpensePerdiem
        /// </summary>
        public virtual SCG.eAccounting.DTO.FnExpenseDocument Expense
        {
            get { return this.expense; }
            set { this.expense = value; }
        }
        /// <summary>
        /// Gets or sets the ReferenceNo for the current FnExpensePerdiem
        /// </summary>
        public virtual string ReferenceNo
        {
            get { return this.referenceNo; }
            set { this.referenceNo = value; }
        }

        /// <summary>
        /// Gets or sets the SaleOrder for the current FnExpensePerdiem
        /// </summary>
        public virtual string SaleOrder
        {
            get { return this.saleOrder; }
            set { this.saleOrder = value; }
        }

        /// <summary>
        /// Gets or sets the SaleItem for the current FnExpensePerdiem
        /// </summary>
        public virtual string SaleItem
        {
            get { return this.saleItem; }
            set { this.saleItem = value; }
        }

        /// <summary>
        /// Gets or sets the Invoice for the current FnExpensePerdiem
        /// </summary>
        public virtual SCG.eAccounting.DTO.FnExpenseInvoice Invoice
        {
            get { return this.invoice; }
            set { this.invoice = value; }
        }

        /// <summary>
        /// Gets or sets the CostCenter for the current FnExpensePerdiem
        /// </summary>
        public virtual SCG.DB.DTO.DbCostCenter CostCenter
        {
            get { return this.costCenter; }
            set { this.costCenter = value; }
        }

        /// <summary>
        /// Gets or sets the Account for the current FnExpensePerdiem
        /// </summary>
        public virtual SCG.DB.DTO.DbAccount Account
        {
            get { return this.account; }
            set { this.account = value; }
        }

        /// <summary>
        /// Gets or sets the IO for the current FnExpensePerdiem
        /// </summary>
        public virtual SCG.DB.DTO.DbInternalOrder IO
        {
            get { return this.iO; }
            set { this.iO = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemRate for the current FnExpensePerdiem
        /// </summary>
        public virtual double PerdiemRate
        {
            get { return this.perdiemRate; }
            set { this.perdiemRate = value; }
        }

        /// <summary>
        /// Gets or sets the PerdiemTotalAmountHigh for the current FnExpensePerdiem
        /// </summary>
        public virtual double PerdiemTotalAmountHigh
        {
            get { return this.perdiemTotalAmountHigh; }
            set { this.perdiemTotalAmountHigh = value; }
        }

        public virtual double PerdiemTotalAmountLocalCurrency
        {
            get { return this.perdiemTotalAmountLocalCurrency; }
            set { this.perdiemTotalAmountLocalCurrency = value; }
        }

        public virtual double PerdiemTotalAmountMainCurrency
        {
            get { return this.perdiemTotalAmountMainCurrency; }
            set { this.perdiemTotalAmountMainCurrency = value; }
        }
        public virtual double PerdiemRateUSDThaiZone
        {
            get { return this.perdiemRateUSDThaiZone; }
            set { this.perdiemRateUSDThaiZone = value; }
        }
        public virtual double PerdiemTotalAmountThaiZone
        {
            get { return this.perdiemTotalAmountThaiZone; }
            set { this.perdiemTotalAmountThaiZone = value; }
        }
        public virtual double TotalFullDayPerdiemThaiZone
        {
            get { return this.totalFullDayPerdiemThaiZone; }
            set { this.totalFullDayPerdiemThaiZone = value; }
        }
        public virtual double FullDayPerdiemRateThaiZone
        {
            get { return this.fullDayPerdiemRateThaiZone; }
            set { this.fullDayPerdiemRateThaiZone = value; }
        }
        public virtual double TotalFullDayPerdiemAmountThaiZone
        {
            get { return this.totalFullDayPerdiemAmountThaiZone; }
            set { this.totalFullDayPerdiemAmountThaiZone = value; }
        }
        public virtual double TotalHalfDayPerdiemThaiZone
        {
            get { return this.totalHalfDayPerdiemThaiZone; }
            set { this.totalHalfDayPerdiemThaiZone = value; }
        }
        public virtual double HalfDayPerdiemRateThaiZone
        {
            get { return this.halfDayPerdiemRateThaiZone; }
            set { this.halfDayPerdiemRateThaiZone = value; }
        }
        public virtual double TotalHalfDayPerdiemAmountThaiZone
        {
            get { return this.totalHalfDayPerdiemAmountThaiZone; }
            set { this.totalHalfDayPerdiemAmountThaiZone = value; }
        }

        #endregion


        #region INHibernateAdapterDTO<long> Members
        public void LoadFromDataRow(DataRow dr)
        {
            this.ExpensePerdiemID = Convert.ToInt64(dr["ExpensePerdiemID"]);
            this.Expense = new FnExpenseDocument(Convert.ToInt64(dr["ExpenseID"]));
            this.Description = dr["Description"].ToString();
            if (!string.IsNullOrEmpty(dr["PerdiemRateUSD"].ToString()))
                this.PerdiemRateUSD = Convert.ToDouble(dr["PerdiemRateUSD"]);
            if (!string.IsNullOrEmpty(dr["PerdiemRateUSDHigh"].ToString()))
                this.PerdiemRateUSDHigh = Convert.ToDouble(dr["PerdiemRateUSDHigh"]);
            this.TotalFullDayPerdiem = Convert.ToDouble(dr["TotalFullDayPerdiem"]);
            this.FullDayPerdiemRate = Convert.ToDouble(dr["FullDayPerdiemRate"]);
            this.TotalFullDayPerdiemAmount = Convert.ToDouble(dr["TotalFullDayPerdiemAmount"]);
            this.TotalHalfDayPerdiem = Convert.ToDouble(dr["TotalHalfDayPerdiem"]);
            this.HalfDayPerdiemRate = Convert.ToDouble(dr["HalfDayPerdiemRate"]);
            this.TotalHalfDayPerdiemAmount = Convert.ToDouble(dr["TotalHalfDayPerdiemAmount"]);
            this.PerdiemGovernmentAmount = Convert.ToDouble(dr["PerdiemGovernmentAmount"]);
            this.PerdiemPrivateAmount = Convert.ToDouble(dr["PerdiemPrivateAmount"]);
            this.PerdiemTaxAmount = Convert.ToDouble(dr["PerdiemTaxAmount"]);
            this.TotalFullDayPerdiemHigh = Convert.ToDouble(dr["TotalFullDayPerdiemHigh"]);
            this.FullDayPerdiemRateHigh = Convert.ToDouble(dr["FullDayPerdiemRateHigh"]);
            this.TotalFullDayPerdiemAmountHigh = Convert.ToDouble(dr["TotalFullDayPerdiemAmountHigh"]);
            this.TotalHalfDayPerdiemHigh = Convert.ToDouble(dr["TotalHalfDayPerdiemHigh"]);
            this.HalfDayPerdiemRateHigh = Convert.ToDouble(dr["HalfDayPerdiemRateHigh"]);
            this.TotalHalfDayPerdiemAmountHigh = Convert.ToDouble(dr["TotalHalfDayPerdiemAmountHigh"]);
            this.ExchangeRate = Convert.ToDouble(dr["ExchangeRate"]);
            this.PerdiemRateGov = Convert.ToDouble(dr["PerdiemRateGov"]);
            this.PerdiemRateGovHigh = Convert.ToDouble(dr["PerdiemRateGovHigh"]);
            this.PerdiemTotalAmountHigh = Convert.ToDouble(dr["PerdiemTotalAmountHigh"]);
            this.PerdiemTotalAmount = Convert.ToDouble(dr["PerdiemTotalAmount"]);
            this.Active = (bool)dr["Active"];
            this.CreBy = Convert.ToInt64(dr["CreBy"].ToString());
            this.CreDate = Convert.ToDateTime(dr["CreDate"]);
            this.UpdBy = Convert.ToInt64(dr["UpdBy"].ToString());
            this.UpdDate = Convert.ToDateTime(dr["UpdDate"]);
            this.UpdPgm = dr["UpdPgm"].ToString();
            this.PerdiemRateUSDHigh = Convert.ToDouble(dr["PerdiemRateUSDHigh"]);
            if (dr["CostCenterID"] != System.DBNull.Value)
                this.CostCenter = new SCG.DB.DTO.DbCostCenter(Convert.ToInt64(dr["CostCenterID"]));
            if (dr["AccountID"] != System.DBNull.Value)
                this.Account = new SCG.DB.DTO.DbAccount(Convert.ToInt64(dr["AccountID"]));
            if (dr["IOID"] != System.DBNull.Value)
                this.IO = new SCG.DB.DTO.DbInternalOrder(Convert.ToInt64(dr["IOID"]));
            this.ReferenceNo = dr["ReferenceNo"].ToString();
            this.SaleOrder = dr["SaleOrder"].ToString();
            this.SaleItem = dr["SaleItem"].ToString();
            this.PerdiemRate = Convert.ToDouble(dr["PerdiemRate"]);
            if (dr["InvoiceID"] != System.DBNull.Value)
                this.Invoice = new FnExpenseInvoice(Convert.ToInt64(dr["InvoiceID"]));
            this.PerdiemTotalAmountLocalCurrency = Convert.ToDouble(dr["PerdiemTotalAmountLocalCurrency"]);
            this.PerdiemTotalAmountMainCurrency = Convert.ToDouble(dr["PerdiemTotalAmountMainCurrency"]);

            this.PerdiemRateUSDThaiZone = Convert.ToDouble(dr["PerdiemRateUSDThaiZone"]);
            this.PerdiemTotalAmountThaiZone = Convert.ToDouble(dr["PerdiemTotalAmountThaiZone"]);
            this.TotalFullDayPerdiemThaiZone = Convert.ToDouble(dr["TotalFullDayPerdiemThaiZone"]);
            this.FullDayPerdiemRateThaiZone = Convert.ToDouble(dr["FullDayPerdiemRateThaiZone"]);
            this.TotalFullDayPerdiemAmountThaiZone = Convert.ToDouble(dr["TotalFullDayPerdiemAmountThaiZone"]);
            this.TotalHalfDayPerdiemThaiZone = Convert.ToDouble(dr["TotalHalfDayPerdiemThaiZone"]);
            this.HalfDayPerdiemRateThaiZone = Convert.ToDouble(dr["HalfDayPerdiemRateThaiZone"]);
            this.TotalHalfDayPerdiemAmountThaiZone = Convert.ToDouble(dr["TotalHalfDayPerdiemAmountThaiZone"]);

        }
        public void SaveIDToDataRow(DataTable dt, DataRow dr, long newID)
        {
            long oldID = dr.Field<long>("ExpensePerdiemID");

            dt.PrimaryKey[0].ReadOnly = false;
            dt.Rows.Find(oldID).BeginEdit();
            dt.Rows.Find(oldID)["ExpensePerdiemID"] = newID;
            dt.Rows.Find(oldID).EndEdit();
            dt.PrimaryKey[0].ReadOnly = true;
        }
        public long GetIDFromDataRow(DataRow dr)
        {
            return Convert.ToInt64(dr["ExpensePerdiemID"].ToString());
        }
        public long GetIDFromDataRow(DataRow dr, DataRowVersion rowState)
        {
            return Convert.ToInt64(dr["ExpensePerdiemID", rowState].ToString());
        }
        #endregion
    }
}
