//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using SS.Standard.Data.NHibernate.DTO;
using SCG.DB.DTO;

namespace SCG.eAccounting.DTO
{
	/// <summary>
	/// POJO for FnExpenseMileage. This class is autogenerated
	/// </summary>
	[Serializable]
	public partial class FnExpenseMileage : INHibernateAdapterDTO<long>
	{
		#region Fields
		
		private long expenseMileageID;
		private string carLicenseNo;
		private string typeOfCar;
		private string owner;
		private string permissionNo;
		private double homeToOfficeRoundTrip;
		private double privateUse;
		private double first100KmRate;
		private double exceed100KmRate;
		private double totalAmount;
		private double helpingAmount;
        private double overHelpingAmount;
		private bool active;
		private long creBy;
		private DateTime creDate;
		private long updBy;
		private DateTime updDate;
		private string updPgm;
        private Byte[] rowVersion;
		private SCG.eAccounting.DTO.FnExpenseDocument expense;
        private SCG.DB.DTO.DbCostCenter costCenter;
        private SCG.DB.DTO.DbAccount account;
        private SCG.DB.DTO.DbInternalOrder iO;
        private bool isOverrideLevel;
        private long? overrideCompanyId;
        private string overrideUserPersonalLevelCode;
        private string overrideLevelRemark;
        private long? currentCompanyId;
        private string currentUserPersonalLevelCode;

		#endregion

		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the FnExpenseMileage class
		/// </summary>
		public FnExpenseMileage()
		{
		}

		public FnExpenseMileage(long expenseMileageID)
		{
			this.expenseMileageID = expenseMileageID;
		}
	
		/// <summary>
		/// Initializes a new instance of the FnExpenseMileage class
		/// </summary>
		/// <param name="carLicenseNo">Initial <see cref="FnExpenseMileage.CarLicenseNo" /> value</param>
		/// <param name="typeOfCar">Initial <see cref="FnExpenseMileage.TypeOfCar" /> value</param>
		/// <param name="owner">Initial <see cref="FnExpenseMileage.Owner" /> value</param>
		/// <param name="permissionNo">Initial <see cref="FnExpenseMileage.PermissionNo" /> value</param>
		/// <param name="homeToOfficeRoundTrip">Initial <see cref="FnExpenseMileage.HomeToOfficeRoundTrip" /> value</param>
		/// <param name="privateUse">Initial <see cref="FnExpenseMileage.PrivateUse" /> value</param>
		/// <param name="first100KmRate">Initial <see cref="FnExpenseMileage.First100KmRate" /> value</param>
		/// <param name="exceed100KmRate">Initial <see cref="FnExpenseMileage.Exceed100KmRate" /> value</param>
		/// <param name="totalAmount">Initial <see cref="FnExpenseMileage.TotalAmount" /> value</param>
		/// <param name="helpingAmount">Initial <see cref="FnExpenseMileage.HelpingAmount" /> value</param>
		/// <param name="aboveHelpingAmount">Initial <see cref="FnExpenseMileage.AboveHelpingAmount" /> value</param>
		/// <param name="active">Initial <see cref="FnExpenseMileage.Active" /> value</param>
		/// <param name="creBy">Initial <see cref="FnExpenseMileage.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="FnExpenseMileage.CreDate" /> value</param>
		/// <param name="updBy">Initial <see cref="FnExpenseMileage.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="FnExpenseMileage.UpdDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="FnExpenseMileage.UpdPgm" /> value</param>
		/// <param name="rowVersion">Initial <see cref="FnExpenseMileage.RowVersion" /> value</param>
		/// <param name="expense">Initial <see cref="FnExpenseMileage.Expense" /> value</param>
        public FnExpenseMileage(string carLicenseNo, string typeOfCar, string owner, string permissionNo, double homeToOfficeRoundTrip, double privateUse, double first100KmRate, double exceed100KmRate, double totalAmount, double helpingAmount, double overHelpingAmount, bool active, long creBy, DateTime creDate, long updBy, DateTime updDate, string updPgm, Byte[] rowVersion, SCG.eAccounting.DTO.FnExpenseDocument expense)
		{
			this.carLicenseNo = carLicenseNo;
			this.typeOfCar = typeOfCar;
			this.owner = owner;
			this.permissionNo = permissionNo;
			this.homeToOfficeRoundTrip = homeToOfficeRoundTrip;
			this.privateUse = privateUse;
			this.first100KmRate = first100KmRate;
			this.exceed100KmRate = exceed100KmRate;
			this.totalAmount = totalAmount;
			this.helpingAmount = helpingAmount;
            this.overHelpingAmount = overHelpingAmount;
			this.active = active;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updBy = updBy;
			this.updDate = updDate;
			this.updPgm = updPgm;
			this.rowVersion = rowVersion;
			this.expense = expense;
		}
	
		/// <summary>
		/// Minimal constructor for class FnExpenseMileage
		/// </summary>
		/// <param name="carLicenseNo">Initial <see cref="FnExpenseMileage.CarLicenseNo" /> value</param>
		/// <param name="typeOfCar">Initial <see cref="FnExpenseMileage.TypeOfCar" /> value</param>
		/// <param name="owner">Initial <see cref="FnExpenseMileage.Owner" /> value</param>
		/// <param name="active">Initial <see cref="FnExpenseMileage.Active" /> value</param>
		/// <param name="creBy">Initial <see cref="FnExpenseMileage.CreBy" /> value</param>
		/// <param name="creDate">Initial <see cref="FnExpenseMileage.CreDate" /> value</param>
		/// <param name="updBy">Initial <see cref="FnExpenseMileage.UpdBy" /> value</param>
		/// <param name="updDate">Initial <see cref="FnExpenseMileage.UpdDate" /> value</param>
		/// <param name="updPgm">Initial <see cref="FnExpenseMileage.UpdPgm" /> value</param>
		public FnExpenseMileage(string carLicenseNo, string typeOfCar, string owner, bool active, long creBy, DateTime creDate, long updBy, DateTime updDate, string updPgm)
		{
			this.carLicenseNo = carLicenseNo;
			this.typeOfCar = typeOfCar;
			this.owner = owner;
			this.active = active;
			this.creBy = creBy;
			this.creDate = creDate;
			this.updBy = updBy;
			this.updDate = updDate;
			this.updPgm = updPgm;
		}
		#endregion
	
		#region Properties
		
		/// <summary>
		/// Gets or sets the ExpenseMileageID for the current FnExpenseMileage
		/// </summary>
		public virtual long ExpenseMileageID
		{
			get { return this.expenseMileageID; }
			set { this.expenseMileageID = value; }
		}
		
		/// <summary>
		/// Gets or sets the CarLicenseNo for the current FnExpenseMileage
		/// </summary>
		public virtual string CarLicenseNo
		{
			get { return this.carLicenseNo; }
			set { this.carLicenseNo = value; }
		}
		
		/// <summary>
		/// Gets or sets the TypeOfCar for the current FnExpenseMileage
		/// </summary>
		public virtual string TypeOfCar
		{
			get { return this.typeOfCar; }
			set { this.typeOfCar = value; }
		}
		
		/// <summary>
		/// Gets or sets the Owner for the current FnExpenseMileage
		/// </summary>
		public virtual string Owner
		{
			get { return this.owner; }
			set { this.owner = value; }
		}
		
		/// <summary>
		/// Gets or sets the PermissionNo for the current FnExpenseMileage
		/// </summary>
		public virtual string PermissionNo
		{
			get { return this.permissionNo; }
			set { this.permissionNo = value; }
		}
		
		/// <summary>
		/// Gets or sets the HomeToOfficeRoundTrip for the current FnExpenseMileage
		/// </summary>
		public virtual double HomeToOfficeRoundTrip
		{
			get { return this.homeToOfficeRoundTrip; }
			set { this.homeToOfficeRoundTrip = value; }
		}
		
		/// <summary>
		/// Gets or sets the PrivateUse for the current FnExpenseMileage
		/// </summary>
		public virtual double PrivateUse
		{
			get { return this.privateUse; }
			set { this.privateUse = value; }
		}
		
		/// <summary>
		/// Gets or sets the First100KmRate for the current FnExpenseMileage
		/// </summary>
		public virtual double First100KmRate
		{
			get { return this.first100KmRate; }
			set { this.first100KmRate = value; }
		}
		
		/// <summary>
		/// Gets or sets the Exceed100KmRate for the current FnExpenseMileage
		/// </summary>
		public virtual double Exceed100KmRate
		{
			get { return this.exceed100KmRate; }
			set { this.exceed100KmRate = value; }
		}
		
		/// <summary>
		/// Gets or sets the TotalAmount for the current FnExpenseMileage
		/// </summary>
		public virtual double TotalAmount
		{
			get { return this.totalAmount; }
			set { this.totalAmount = value; }
		}
		
		/// <summary>
		/// Gets or sets the HelpingAmount for the current FnExpenseMileage
		/// </summary>
		public virtual double HelpingAmount
		{
			get { return this.helpingAmount; }
			set { this.helpingAmount = value; }
		}
		
		/// <summary>
		/// Gets or sets the AboveHelpingAmount for the current FnExpenseMileage
		/// </summary>
        public virtual double OverHelpingAmount
		{
            get { return this.overHelpingAmount; }
            set { this.overHelpingAmount = value; }
		}
		
		/// <summary>
		/// Gets or sets the Active for the current FnExpenseMileage
		/// </summary>
		public virtual bool Active
		{
			get { return this.active; }
			set { this.active = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreBy for the current FnExpenseMileage
		/// </summary>
		public virtual long CreBy
		{
			get { return this.creBy; }
			set { this.creBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the CreDate for the current FnExpenseMileage
		/// </summary>
		public virtual DateTime CreDate
		{
			get { return this.creDate; }
			set { this.creDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdBy for the current FnExpenseMileage
		/// </summary>
		public virtual long UpdBy
		{
			get { return this.updBy; }
			set { this.updBy = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdDate for the current FnExpenseMileage
		/// </summary>
		public virtual DateTime UpdDate
		{
			get { return this.updDate; }
			set { this.updDate = value; }
		}
		
		/// <summary>
		/// Gets or sets the UpdPgm for the current FnExpenseMileage
		/// </summary>
		public virtual string UpdPgm
		{
			get { return this.updPgm; }
			set { this.updPgm = value; }
		}
		
		/// <summary>
		/// Gets or sets the RowVersion for the current FnExpenseMileage
		/// </summary>
        public virtual Byte[] RowVersion
		{
			get { return this.rowVersion; }
			set { this.rowVersion = value; }
		}
		
		/// <summary>
		/// Gets or sets the Expense for the current FnExpenseMileage
		/// </summary>
		public virtual SCG.eAccounting.DTO.FnExpenseDocument Expense
		{
			get { return this.expense; }
			set { this.expense = value; }
		}

        /// <summary>
        /// Gets or sets the CostCenter for the current FnExpenseMileage
        /// </summary>
        public virtual SCG.DB.DTO.DbCostCenter CostCenter
        {
            get { return this.costCenter; }
            set { this.costCenter = value; }
        }

        /// <summary>
        /// Gets or sets the Account for the current FnExpenseMileage
        /// </summary>
        public virtual SCG.DB.DTO.DbAccount Account
        {
            get { return this.account; }
            set { this.account = value; }
        }

        /// <summary>
        /// Gets or sets the IO for the current FnExpenseMileage
        /// </summary>
        public virtual SCG.DB.DTO.DbInternalOrder IO
        {
            get { return this.iO; }
            set { this.iO = value; }
        }

        public virtual bool IsOverrideLevel 
        {
            get { return this.isOverrideLevel; }
            set { this.isOverrideLevel = value; }
        }


        public virtual long? OverrideCompanyId
        {
            get { return this.overrideCompanyId; }
            set { this.overrideCompanyId = value; }
        }

        public virtual string OverrideUserPersonalLevelCode
        {
            get { return this.overrideUserPersonalLevelCode; }
            set { this.overrideUserPersonalLevelCode = value; }
        }

        public virtual string OverrideLevelRemark
        {
            get { return this.overrideLevelRemark; }
            set { this.overrideLevelRemark = value; }
        }

        public virtual long? CurrentCompanyId
        {
            get { return this.currentCompanyId; }
            set { this.currentCompanyId = value; }
        }

        public virtual string CurrentUserPersonalLevelCode
        {
            get { return this.currentUserPersonalLevelCode; }
            set { this.currentUserPersonalLevelCode = value; }
        }

		#endregion

        #region INHibernateAdapterDTO<long> Members
        public void LoadFromDataRow(DataRow dr)
        {
            this.ExpenseMileageID = Convert.ToInt64(dr["ExpenseMileageID"]);
            this.Expense = new FnExpenseDocument(Convert.ToInt64(dr["ExpenseID"]));
            this.CarLicenseNo = dr["CarLicenseNo"].ToString();
            this.TypeOfCar = dr["TypeOfCar"].ToString();
            this.Owner = dr["Owner"].ToString();
            this.PermissionNo = dr["PermissionNo"].ToString();
            this.HomeToOfficeRoundTrip = Convert.ToDouble(dr["HomeToOfficeRoundTrip"]);
            this.PrivateUse = Convert.ToDouble(dr["PrivateUse"]);
            this.First100KmRate = Convert.ToDouble(dr["First100KmRate"]);
            this.Exceed100KmRate = Convert.ToDouble(dr["Exceed100KmRate"]);
            this.TotalAmount = Convert.ToDouble(dr["TotalAmount"]);
            this.HelpingAmount = Convert.ToDouble(dr["HelpingAmount"]);
            this.OverHelpingAmount = Convert.ToDouble(dr["OverHelpingAmount"]);
            this.Active = (bool)dr["Active"];
            this.CreBy = Convert.ToInt64(dr["CreBy"].ToString());
            this.CreDate = Convert.ToDateTime(dr["CreDate"]);
            this.UpdBy = Convert.ToInt64(dr["UpdBy"].ToString());
            this.UpdDate = Convert.ToDateTime(dr["UpdDate"]);
            this.UpdPgm = dr["UpdPgm"].ToString();

            this.CostCenter =
                (dr["CostCenterID"] == System.DBNull.Value ? null : new DbCostCenter(Convert.ToInt64(dr["CostCenterID"])));
            this.Account =
                (dr["AccountID"] == System.DBNull.Value ? null : new DbAccount(Convert.ToInt64(dr["AccountID"])));
            this.IO =
                (dr["IOID"] == System.DBNull.Value ? null : new DbInternalOrder(Convert.ToInt64(dr["IOID"])));

            this.IsOverrideLevel = (bool)dr["IsOverrideLevel"];

            if (!string.IsNullOrEmpty(dr["OverrideCompanyId"].ToString()))
            {
                this.OverrideCompanyId = Convert.ToInt64(dr["OverrideCompanyId"]);
            }
            this.OverrideUserPersonalLevelCode = dr["OverrideUserPersonalLevelCode"].ToString();
            this.OverrideLevelRemark = dr["OverrideLevelRemark"].ToString();
            if (!string.IsNullOrEmpty(dr["CurrentCompanyId"].ToString()))
            {
                this.CurrentCompanyId = Convert.ToInt64(dr["CurrentCompanyId"]);
            }
            this.CurrentUserPersonalLevelCode = dr["CurrentUserPersonalLevelCode"].ToString();
        }
        public void SaveIDToDataRow(DataTable dt, DataRow dr, long newID)
        {
            long oldID = dr.Field<long>("ExpenseMileageID");

            dt.PrimaryKey[0].ReadOnly = false;
            dt.Rows.Find(oldID).BeginEdit();
            dt.Rows.Find(oldID)["ExpenseMileageID"] = newID;
            dt.Rows.Find(oldID).EndEdit();
            dt.PrimaryKey[0].ReadOnly = true;
        }
        public long GetIDFromDataRow(DataRow dr)
        {
            return Convert.ToInt64(dr["ExpenseMileageID"].ToString());
        }
        public long GetIDFromDataRow(DataRow dr, DataRowVersion rowState)
        {
            return Convert.ToInt64(dr["ExpenseMileageID", rowState].ToString());
        }
        #endregion
	}
}
